// Curated commercial gym equipment catalog — 250+ items across 10 major brands.
// Gym owners pick from this to populate their inventory. Anything missing can be
// added via the AI Web Search feature (see lib/ai.js → searchEquipmentOnWeb).
//
// Schema:
//   id          unique string id
//   brand       manufacturer name (matches BRAND_WEBSITES keys in constants.js)
//   name        display name
//   category    Machine | Cable | Free Weight | Cardio
//   targetArea  comma-separated muscle groups
//   minWeight, maxWeight  numeric strings in pounds ("0" if N/A)
//   instructions  short usage guide shown to members
//   image       photo URL

export const GLOBAL_EQUIPMENT_DATABASE = [

  // ═══════════════════════════════════════════════════════════════
  // ROGUE FITNESS — Barbells & Free Weights
  // ═══════════════════════════════════════════════════════════════
  { id:'rg_bar1', brand:'Rogue Fitness', name:'Ohio Bar – Cerakote (20kg)', category:'Free Weight', targetArea:'Full Body, Olympic Lifts, Powerlifting', minWeight:'45', maxWeight:'1500', instructions:'Standard 45 lb/20 kg Olympic barbell. Load plates symmetrically. Fasten collars before lifting. Center knurling aids upper-back grip for squats. 190k PSI tensile strength shaft.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-OHIOCERAKOTE/AU-OHIOCERAKOTE-TH_oljo13.png' },
  { id:'rg_bar2', brand:'Rogue Fitness', name:'Ohio Deadlift Bar', category:'Free Weight', targetArea:'Posterior Chain, Hamstrings, Glutes, Lower Back', minWeight:'44', maxWeight:'1000', instructions:'27mm whip bar for conventional and sumo deadlifts. More aggressive knurling for grip. Allow bar to flex before plates break the floor — this reduces the initial pull demand. Used in competitive powerlifting.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-OHIOCERAKOTE/AU-OHIOCERAKOTE-TH_oljo13.png' },
  { id:'rg_bar3', brand:'Rogue Fitness', name:"Bella Bar 2.0 (15kg Women's)", category:'Free Weight', targetArea:'Full Body, Olympic Lifts', minWeight:'33', maxWeight:'750', instructions:"15 kg/33 lb women's Olympic barbell with 25mm diameter shaft. Shorter distance between sleeves suits standard female proportions. Use for snatches, cleans, jerks, and general strength training.", image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-OHIOCERAKOTE/AU-OHIOCERAKOTE-TH_oljo13.png' },
  { id:'rg_bar4', brand:'Rogue Fitness', name:'Safety Squat Bar (SSB)', category:'Free Weight', targetArea:'Quadriceps, Glutes, Hamstrings, Core', minWeight:'60', maxWeight:'1000', instructions:'Yoke-style padding rests on shoulders. Handles face forward reducing upper back and shoulder strain. Great for athletes with shoulder mobility issues. Slightly more forward lean than a straight bar — recruit quads aggressively.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-OHIOCERAKOTE/AU-OHIOCERAKOTE-TH_oljo13.png' },
  { id:'rg_bar5', brand:'Rogue Fitness', name:'Curl Bar / EZ Bar', category:'Free Weight', targetArea:'Biceps, Forearms, Triceps', minWeight:'15', maxWeight:'200', instructions:'Angled grip reduces wrist supination stress vs straight bar. Inner grip for more bicep peak; outer grip for lower biceps. Load with Olympic plates. Keep elbows fixed at sides during curls.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-OHIOCERAKOTE/AU-OHIOCERAKOTE-TH_oljo13.png' },
  { id:'rg_bar6', brand:'Rogue Fitness', name:'Multi-Grip Bar / Swiss Bar', category:'Free Weight', targetArea:'Chest, Triceps, Shoulders – Neutral Grip', minWeight:'35', maxWeight:'700', instructions:'Multiple neutral grip positions allow bench press, overhead press, and rows with reduced shoulder strain. Parallel grip eliminates wrist pronation. Excellent for athletes with shoulder or elbow injuries preventing standard bar pressing.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-OHIOCERAKOTE/AU-OHIOCERAKOTE-TH_oljo13.png' },
  { id:'rg_wt1', brand:'Rogue Fitness', name:'HG 2.0 Bumper Plates (10–45 lb)', category:'Free Weight', targetArea:'Full Body', minWeight:'10', maxWeight:'45', instructions:'Designed for dropping from overhead during Olympic lifts. Load symmetrically. Use on rubber flooring only. Inspect for cracks before each session.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Plates/Bumper%20Plates/IP0125/IP0125-TH_htw9hf.png' },
  { id:'rg_wt2', brand:'Rogue Fitness', name:'Calibrated KG Steel Plates', category:'Free Weight', targetArea:'Full Body', minWeight:'0.25', maxWeight:'25', instructions:'Precision-calibrated to ±10g per plate. Used in competitive powerlifting. Load heaviest plates first. Handle carefully — contact with rubber bumpers can damage calibration.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Plates/Bumper%20Plates/IP0125/IP0125-TH_htw9hf.png' },
  { id:'rg_wt3', brand:'Rogue Fitness', name:'Dumbbell Set (5–100 lb)', category:'Free Weight', targetArea:'Full Body', minWeight:'5', maxWeight:'100', instructions:'Urethane-coated hex dumbbells. Select weight where last 2 reps of each set are challenging. Return to rack by size after use. Check end caps before each set.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Strength%20Equipment/Kettlebells/USC001-PC/USC001-PC-TH_fyhrze.png' },
  { id:'rg_wt4', brand:'Rogue Fitness', name:'Kettlebell Set (8–48 kg)', category:'Free Weight', targetArea:'Full Body, Core, Cardiovascular', minWeight:'18', maxWeight:'106', instructions:'Single-cast iron construction. For swings: hike bell back, drive hips forward explosively. For cleans: keep bell close, rotate elbow under at top. For Turkish get-up: maintain locked wrist with eyes on bell.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Strength%20Equipment/Kettlebells/USC001-PC/USC001-PC-TH_fyhrze.png' },
  { id:'rg_wt5', brand:'Rogue Fitness', name:'OSO Barbell Collars', category:'Free Weight', targetArea:'N/A – Safety Accessory', minWeight:'0', maxWeight:'0', instructions:'Twist-lock collar. Slide onto sleeve, twist to lock. Withstands drops from overhead. Check lock before every heavy set. Inspect threads monthly for wear.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Collars/OSO%20Collars/RA1571-AN-GM/RA1571-AN-GM-TH_cqk5oz.png' },

  // ═══════════════════════════════════════════════════════════════
  // ROGUE FITNESS — Racks & Rigs
  // ═══════════════════════════════════════════════════════════════
  { id:'rg_rack1', brand:'Rogue Fitness', name:'Monster RM-4 Power Rack', category:'Free Weight', targetArea:'Full Body – Squat, Bench, OHP, Deadlift', minWeight:'0', maxWeight:'1000', instructions:'3x3" 11-gauge steel uprights. Set J-Cups at hip height for squats. Install safety spotter arms at the level the bar would be if you failed a rep. Pull-up bar at top for bodyweight work.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Power%20Racks%20/Monster%20Racks/RM-4/RM-4-SATIN-BLACK-TH_qvulup.png' },
  { id:'rg_rack2', brand:'Rogue Fitness', name:'Monster RM-6 Power Rack', category:'Free Weight', targetArea:'Full Body – Squat, Bench, OHP', minWeight:'0', maxWeight:'1000', instructions:'Extended depth version of the RM-4. More usable space inside the rack. Ideal for in-rack deadlifts or when multiple athletes use the same rack simultaneously.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Power%20Racks%20/Monster%20Racks/RM-4/RM-4-SATIN-BLACK-TH_qvulup.png' },
  { id:'rg_rack3', brand:'Rogue Fitness', name:'Monster Lite SML-2 Squat Stand', category:'Free Weight', targetArea:'Legs, Chest, Shoulders', minWeight:'0', maxWeight:'1000', instructions:'Set J-Cups at hip height. Safety spotter arms MUST be positioned before un-racking any weight. More open than a full rack — ideal for athletes who prefer external spotters.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Squat%20Stands/Monster%20Lite%20Squat%20Stands/AU-SML2/AU-SML2-th_yoeyqn.png' },
  { id:'rg_rack4', brand:'Rogue Fitness', name:'Monster Half Rack HR-2', category:'Free Weight', targetArea:'Full Body – Pull-ups, Squat, Bench', minWeight:'0', maxWeight:'700', instructions:'Half rack with multi-grip pull-up bar. Requires wall anchor or weight-horn loading for stability. Compatible with Monster attachments. Great for smaller facilities.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Power%20Racks%20/Monster%20Lite%20Racks/AU-RML690/AU-RML690-th_enxjsl.png' },

  // ═══════════════════════════════════════════════════════════════
  // ROGUE FITNESS — Rack Attachments
  // ═══════════════════════════════════════════════════════════════
  { id:'rg_att1', brand:'Rogue Fitness', name:'Monster Lat Pulldown / Low Row', category:'Cable', targetArea:'Latissimus Dorsi, Biceps, Mid-Back', minWeight:'0', maxWeight:'250', instructions:'Rack-mounted cable system for any Monster Series rack. Install via uprights. Attach desired handle. Use seat position for pulldowns; floor position for low rows.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Rig%20and%20Rack%20Accessories/Monster%20Lite%20Accessories/RA0383/RA0383-TH_m9abi4.png' },
  { id:'rg_att2', brand:'Rogue Fitness', name:'Monster Landmine 2.0', category:'Free Weight', targetArea:'Core, Shoulders, Chest, Back – Rotational Power', minWeight:'0', maxWeight:'300', instructions:'Pivots in all directions. Mount to any Monster Series upright. Use with football bar or regular barbell. Great for anti-rotation core work, single-arm press, and meadows rows.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Rig%20and%20Rack%20Accessories/Monster%20Lite%20Accessories/RA0383/RA0383-TH_m9abi4.png' },
  { id:'rg_att3', brand:'Rogue Fitness', name:'Monster Rhino Belt Squat', category:'Machine', targetArea:'Quadriceps, Glutes, Hamstrings', minWeight:'45', maxWeight:'600', instructions:'Drop-in attachment for Monster racks. Attach hip belt. Load plates on weight horns. Squat with load at hips — eliminates axial spine loading. Great for leg development while resting the back.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Rig%20and%20Rack%20Accessories/Monster%20Lite%20Accessories/RA0383/RA0383-TH_m9abi4.png' },
  { id:'rg_att4', brand:'Rogue Fitness', name:'Band Pegs (Monster Series)', category:'Free Weight', targetArea:'Full Body – Variable Resistance', minWeight:'0', maxWeight:'0', instructions:'11" steel pegs attach to rack uprights. Loop resistance bands for accommodating resistance on squats, deadlifts, and bench press. More resistance at lockout.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Rig%20and%20Rack%20Accessories/Monster%20Lite%20Accessories/RA0383/RA0383-TH_m9abi4.png' },
  { id:'rg_att5', brand:'Rogue Fitness', name:'Monster Dip Station', category:'Free Weight', targetArea:'Triceps, Chest, Shoulders – Weighted Dips', minWeight:'0', maxWeight:'400', instructions:'Mounts to rack uprights. Grip bars slightly wider than shoulders. Lower until upper arms are parallel to floor. Press back up. Upright torso = more triceps; forward lean = more chest.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Rig%20and%20Rack%20Accessories/Monster%20Lite%20Accessories/RA0383/RA0383-TH_m9abi4.png' },

  // ═══════════════════════════════════════════════════════════════
  // ROGUE FITNESS — Strength Training
  // ═══════════════════════════════════════════════════════════════
  { id:'rg_str1', brand:'Rogue Fitness', name:'Adjustable Bench AB-3', category:'Free Weight', targetArea:'Chest, Shoulders, Triceps, Back', minWeight:'0', maxWeight:'1000', instructions:'Set angle: flat (0°) for bench press, 30-45° incline for upper chest, 15° decline for lower chest. Lock angle pin before loading. Pad should support full back from hips to head.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Weight%20Benches/Adjustable%20:%20Incline%20Benches/RF0935/RF0935-MG-Black-TH_vj8tsi.png' },
  { id:'rg_str2', brand:'Rogue Fitness', name:'GHD 2.0 – Glute Ham Developer', category:'Machine', targetArea:'Glutes, Hamstrings, Lower Back, Core', minWeight:'0', maxWeight:'0', instructions:'Adjust foot plate so hips rest at the pad edge. GHD sit-ups initiate from hip flexors; back extensions from glutes. Add a weight plate at chest for progression. Beginners use hands on chest until form mastered.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Weight%20Benches/Adjustable%20:%20Incline%20Benches/RF0935/RF0935-MG-Black-TH_vj8tsi.png' },
  { id:'rg_str3', brand:'Rogue Fitness', name:'Reverse Hyper RH-2', category:'Machine', targetArea:'Lower Back, Glutes, Hamstrings', minWeight:'0', maxWeight:'200', instructions:'Lie prone with hips at pad edge. Grip handles firmly. Swing legs back and up to parallel — squeeze glutes at top. Lower slowly. Pendulum effect amplifies resistance; start with very light weight.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Rigs%20and%20Racks/Rig%20and%20Rack%20Accessories/RA2717/RA2717-MG-Black-Stainless-Roller-Cart-TH_rrapkn.png' },
  { id:'rg_str4', brand:'Rogue Fitness', name:'V-2 Sled', category:'Cardio', targetArea:'Legs, Glutes, Calves, Cardiovascular', minWeight:'0', maxWeight:'500', instructions:'Load weight evenly on posts. Push with arms extended at 45° forward lean. For drag: attach belt and walk backward. Keep core braced. Best in 20-40 yard intervals with full recovery.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Strength%20Equipment/Kettlebells/USC001-PC/USC001-PC-TH_fyhrze.png' },
  { id:'rg_str5', brand:'Rogue Fitness', name:'AbMat', category:'Machine', targetArea:'Core, Abdominals, Hip Flexors', minWeight:'0', maxWeight:'0', instructions:'Thick end faces glutes. Mat supports lumbar curve and allows full spinal extension at the bottom — impossible on the floor alone. Dramatically increases abdominal recruitment.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Bodyweight%20and%20Gymnastics/Bodyweight%20/AbMats/AU-AB0006/AU-AB0006-TH_ckagj6.png' },
  { id:'rg_str6', brand:'Rogue Fitness', name:'Monster Yoke', category:'Free Weight', targetArea:'Legs, Core, Traps, Full Body – Strongman', minWeight:'0', maxWeight:'2000', instructions:'Load plates on both ends. Walk frame across floor maintaining upright torso. Builds posterior chain strength and grip endurance. Use flat-soled footwear for stability.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Strength%20Equipment/Kettlebells/USC001-PC/USC001-PC-TH_fyhrze.png' },

  // ═══════════════════════════════════════════════════════════════
  // ROGUE FITNESS — Cardio & Functional Trainers
  // ═══════════════════════════════════════════════════════════════
  { id:'rg_c1', brand:'Rogue Fitness', name:'Echo Bike V3', category:'Cardio', targetArea:'Full Body, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Adjust seat so leg is slightly bent at bottom. Push and pull arms simultaneously. Resistance increases automatically with effort — no speed limit. Used for Assault Bike intervals and AMRAP conditioning.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Endurance%20/Bikes/AU-ECHOBIKE/AU-ECHOBIKE-TH_h7wo7i.png' },
  { id:'rg_c2', brand:'Rogue Fitness', name:'Echo Rower', category:'Cardio', targetArea:'Full Body, Back, Legs, Cardiovascular', minWeight:'0', maxWeight:'500', instructions:'Strap feet in. Drive legs, hinge hips back, pull handle to lower chest — in that order. Return: arms out, hinge forward, knees bend. Monitor tracks split time per 500m, watts, and stroke rate.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Endurance%20/Bikes/AU-ECHOBIKE/AU-ECHOBIKE-TH_h7wo7i.png' },
  { id:'rg_c3', brand:'Rogue Fitness', name:'Concept2 RowErg (PM5)', category:'Cardio', targetArea:'Legs, Back, Core, Arms, Cardiovascular', minWeight:'0', maxWeight:'500', instructions:'Strap feet in. Drive with legs, lean hips back, then pull handle to lower ribs. Reverse on recovery. Damper 3-5 typical for most athletes. Track split time per 500m on the PM5.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Endurance%20/Bikes/AU-ECHOBIKE/AU-ECHOBIKE-TH_h7wo7i.png' },
  { id:'rg_c4', brand:'Rogue Fitness', name:'SkiErg 2', category:'Cardio', targetArea:'Upper Body, Lats, Core, Triceps, Cardiovascular', minWeight:'0', maxWeight:'0', instructions:'Stand facing machine, grip handles overhead. Pull both handles down past hips in a diagonal skiing motion. Drive with core and lats, not just arms. Can alternate arms for cross-country ski pattern.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Endurance%20/Bikes/AU-ECHOBIKE/AU-ECHOBIKE-TH_h7wo7i.png' },
  { id:'rg_ft1', brand:'Rogue Fitness', name:'FX-1 Functional Trainer', category:'Cable', targetArea:'Full Body – Chest, Back, Shoulders, Arms, Core, Legs', minWeight:'5', maxWeight:'200', instructions:'Adjust both carriages independently. Attach desired handle. Select weight via pop-pin. Great for cable flyes, split-stance rows, chops, face pulls, and unilateral pressing patterns.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/FX-1%20Functional%20Trainer/FX-1%20Functional%20Trainer%20%2B%20RM-6/Red-FT-weight-stack-TH_ttjrpy.png' },
  { id:'rg_ft2', brand:'Rogue Fitness', name:'CG-1 Cable & Landmine Attachment', category:'Cable', targetArea:'Full Body – Rotational, Pressing, Pulling', minWeight:'0', maxWeight:'200', instructions:'Dual-purpose: cable attachment or landmine press handle. Single carriage with rotating connection. Works with any standard carabiner. Great for cable curls, pushdowns, and landmine press variations.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/FX-1%20Functional%20Trainer/FX-1%20Functional%20Trainer%20%2B%20RM-6/Red-FT-weight-stack-TH_ttjrpy.png' },

  // ═══════════════════════════════════════════════════════════════
  // CABLE ATTACHMENTS — Universal
  // ═══════════════════════════════════════════════════════════════
  { id:'ca_1',  brand:'Cable Attachments', name:'Standard Lat Pulldown Bar (48")', category:'Cable', targetArea:'Latissimus Dorsi, Biceps, Rear Deltoids', minWeight:'0', maxWeight:'0', instructions:'Grip slightly wider than shoulder-width overhand. Pull bar to upper chest, elbows driving down and back. Squeeze shoulder blades together at bottom. Return slowly to full arm extension.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_2',  brand:'Cable Attachments', name:'D-Handle / Stirrup Handle', category:'Cable', targetArea:'Full Body – Unilateral Pulling, Pressing, Curls', minWeight:'0', maxWeight:'0', instructions:'Clip to cable with carabiner. Single handle for unilateral training. Use for single-arm rows, curls, lateral raises, tricep pushdowns, oblique twists, and cable crossovers. Rotating swivel prevents wrist strain.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_3',  brand:'Cable Attachments', name:'Tricep Rope', category:'Cable', targetArea:'Triceps, Rear Deltoids, Core', minWeight:'0', maxWeight:'0', instructions:'Grip both ends. For pushdowns: press down splitting rope apart at bottom for full tricep extension. For face pulls: pull to face splitting rope at ear level. For crunches: hold rope overhead and crunch down. Greater ROM than rigid bars.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_4',  brand:'Cable Attachments', name:'V-Bar / Tricep Pressdown Bar', category:'Cable', targetArea:'Triceps, Forearms', minWeight:'0', maxWeight:'0', instructions:'Neutral parallel grip reduces wrist pronation stress. Attach to high cable. Stand close, elbows tight to sides, press down to full extension. Hold 1 second at bottom. Can handle slightly heavier loads than rope.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_5',  brand:'Cable Attachments', name:'Straight Bar / Long Straight Bar', category:'Cable', targetArea:'Biceps, Triceps, Back, Forearms', minWeight:'0', maxWeight:'0', instructions:'Overhand for tricep pushdowns and pulldowns. Underhand for bicep curls. Keep elbows fixed at sides for arm isolation. Full ROM from full extension to full contraction essential.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_6',  brand:'Cable Attachments', name:'EZ-Curl Cable Bar', category:'Cable', targetArea:'Biceps, Forearms, Triceps', minWeight:'0', maxWeight:'0', instructions:'Angled grips reduce wrist supination strain. Inner grip for bicep peak; outer grip for lower biceps. Use for overhead tricep extensions with high cable. Swap with straight bar when wrist discomfort occurs.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_7',  brand:'Cable Attachments', name:'Ankle Strap Cuff', category:'Cable', targetArea:'Glutes, Hamstrings, Hip Abductors, Quadriceps', minWeight:'0', maxWeight:'0', instructions:'Velcro around ankle, clip D-ring to low cable. Face away for kickbacks (glutes). Face machine for standing leg curls (hamstrings). Stand sideways for side kicks (hip abductors). Hold machine for balance.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'ca_8',  brand:'Cable Attachments', name:'Double D-Handle / Rowing Handle', category:'Cable', targetArea:'Mid-Back, Rhomboids, Biceps, Rear Deltoids', minWeight:'0', maxWeight:'0', instructions:'Two parallel D-handles on a spreader bar for seated cable rows. Neutral grip reduces shoulder strain. Pull handles to lower abs, squeezing shoulder blades together. Heavy rowing possible with secure grip.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_9',  brand:'Cable Attachments', name:'Multi-Grip Bar (Cable)', category:'Cable', targetArea:'Biceps, Back, Triceps – Neutral Grip', minWeight:'0', maxWeight:'0', instructions:'Multiple neutral grip positions for various pull and push angles. Great for neutral-grip pulldowns, hammer curl variations, and face pulls. Hammer grip reduces elbow stress vs supinated positions.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_10', brand:'Cable Attachments', name:'Ab Strap / Crunch Strap', category:'Cable', targetArea:'Rectus Abdominis, Obliques, Hip Flexors', minWeight:'0', maxWeight:'0', instructions:'Loop straps over forearms. Attach to high cable. Kneel facing away. Crunch torso downward contracting abs — NOT pulling with arms. Return with control. Rotate for obliques.', image:'https://images.unsplash.com/photo-1571019614242-c5c5adee9f50?q=80&w=1000' },
  { id:'ca_11', brand:'Cable Attachments', name:'Rotating Single Handle', category:'Cable', targetArea:'Full Body – Wrist-Neutral Unilateral', minWeight:'0', maxWeight:'0', instructions:'360° rotating connection neutralizes wrist torque. Use when D-handle causes wrist discomfort. Ideal for cable flyes, curls, and single-arm pushdowns. Chrome or aircraft aluminum construction.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_12', brand:'Cable Attachments', name:'Close-Grip Lat Bar (Neutral)', category:'Cable', targetArea:'Latissimus Dorsi, Biceps, Teres Major', minWeight:'0', maxWeight:'0', instructions:'Parallel neutral grip handles. Pull to upper chest with elbows driving straight down. Neutral grip allows slightly more load and reduces shoulder impingement risk vs overhand. Great for beginners.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_13', brand:'Cable Attachments', name:'Seated Row V-Grip Handle', category:'Cable', targetArea:'Mid-Back, Rhomboids, Lower Trapezius', minWeight:'0', maxWeight:'0', instructions:'Compact V-handle for seated cable rows. Sit upright, slight knee bend. Pull handle to lower sternum. Return to full arm extension. V-angle provides neutral grip for maximum mid-back engagement.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_14', brand:'Cable Attachments', name:'Revolving Straight Bar', category:'Cable', targetArea:'Biceps, Back, Shoulders', minWeight:'0', maxWeight:'0', instructions:'Rotating sleeve allows wrists to naturally supinate during curls and pronate during pulldowns. Reduces forearm and wrist fatigue. Use for lat pulldowns, bicep curls, upright rows, and face pulls.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_15', brand:'Cable Attachments', name:'Landmine T-Bar Handle', category:'Free Weight', targetArea:'Back, Core, Shoulders – Rotational Movements', minWeight:'0', maxWeight:'300', instructions:'Insert one end of barbell into landmine attachment. Grip T-handle with both hands. Use for landmine rows, landmine press, and rotational sweeps. Single-arm variations build unilateral stability.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'ca_16', brand:'Cable Attachments', name:'Single Tricep Rope (Unilateral)', category:'Cable', targetArea:'Triceps – Unilateral Training', minWeight:'0', maxWeight:'0', instructions:'Single rope (not looped) for one-handed tricep work. 15" long with rubber stopper. Use for single-arm pushdowns and overhead extensions. Eliminates dominant arm compensation. Great for addressing tricep imbalances.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'ca_17', brand:'Cable Attachments', name:'Hip Belt / Dip Belt for Cable', category:'Cable', targetArea:'Glutes, Hamstrings, Hips – Cable Pull-Through', minWeight:'0', maxWeight:'0', instructions:'Loop belt around hips, attach to low cable between legs. Hinge forward, drive hips forward to full extension — like a cable deadlift or pull-through. Isolates glutes and hip extensors. Excellent glute activation tool.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'ca_18', brand:'Cable Attachments', name:'Wrist Roller Attachment', category:'Cable', targetArea:'Forearms, Grip Strength, Wrists', minWeight:'0', maxWeight:'0', instructions:'Attach to low cable. Hold handle and perform wrist curls or rotations. Trains forearm flexors and extensors through isolated wrist movement. Essential for grip-dependent sports and general grip strength development.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // LIFE FITNESS — Cardio
  // ═══════════════════════════════════════════════════════════════
  { id:'lf_c1', brand:'Life Fitness', name:'Club Series+ Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Attach safety clip before starting. FlexDeck cushioning reduces impact by up to 30%. Adjust speed incrementally. Use incline intervals (6-10%) to increase calorie burn without increasing speed.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'lf_c2', brand:'Life Fitness', name:'Symbio Incline Elliptical', category:'Cardio', targetArea:'Full Body, Glutes, Legs, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Higher incline targets glutes more aggressively. Moving handlebars engage upper body. Reduce grip pressure to increase core engagement. Use Symbio touchscreen for heart rate zone training.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'lf_c3', brand:'Life Fitness', name:'CLST Recumbent Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Adjust seat so leg reaches near full extension. Recline into supportive backrest. Step-through frame for easy entry. Ideal for post-injury rehabilitation and users with lower back sensitivity.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'lf_c4', brand:'Life Fitness', name:'IC8 Indoor Cycling Bike (ICG)', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Set seat height to hip height standing beside bike. Knee slightly forward of pedal at bottom. Resistance dial controls flywheel friction. LED console tracks power in watts for data-driven training.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'lf_c5', brand:'Life Fitness', name:'PowerMill Stair Climber', category:'Cardio', targetArea:'Glutes, Quadriceps, Calves, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Do NOT lean on handrails. Take full steps for glute emphasis. Short quick steps increase cardiovascular demand. Excellent HIIT platform: 30-second max efforts with 30-second recovery.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'lf_c6', brand:'Life Fitness', name:'Atmos Treadmill (Compact)', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Compact footprint for hotel and multi-unit spaces. Same FlexDeck cushioning as Club Series. SL LED or SE4 touchscreen console. Designed for walking, jogging, and light running.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'lf_c7', brand:'Life Fitness', name:'Atmos Elliptical (Compact)', category:'Cardio', targetArea:'Full Body, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Compact commercial elliptical for space-constrained facilities. Pairs with Atmos Treadmill and Bike. SL or SE4 console. Natural stride path minimizes joint stress.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'lf_c8', brand:'Life Fitness', name:'Atmos Upright Bike (Compact)', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'300', instructions:'Compact upright bike completing the Atmos cardio line. Adjust seat height for slight knee bend. Magnetic resistance for quiet operation. SL console. Great for hotel fitness rooms and limited-space facilities.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // LIFE FITNESS — Insignia Selectorized Strength
  // ═══════════════════════════════════════════════════════════════
  { id:'lf_s1',  brand:'Life Fitness', name:'Insignia Chest Press', category:'Machine', targetArea:'Pectoralis Major, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'250', instructions:'Adjust seat so handles align at mid-chest. Converging press arc. Return with control. Keep shoulder blades retracted and back flat against pad throughout.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s2',  brand:'Life Fitness', name:'Insignia Incline Chest Press', category:'Machine', targetArea:'Upper Pectoralis, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'220', instructions:'Higher seat targets upper chest. Converging arc closes hands slightly at peak contraction. Use lighter weight than flat chest press. Keep head against pad.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s3',  brand:'Life Fitness', name:'Insignia Lat Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Biceps, Rear Deltoids', minWeight:'10', maxWeight:'250', instructions:'Set knee pad snugly. Overhand grip slightly wider than shoulders. Pull bar to upper chest. Keep chest up, elbows driving down and back. Return slowly to maintain tension.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s4',  brand:'Life Fitness', name:'Insignia Seated Cable Row', category:'Machine', targetArea:'Mid-Back, Rhomboids, Biceps, Rear Deltoids', minWeight:'10', maxWeight:'250', instructions:'Chest against pad. Row elbows back past torso, squeezing shoulder blades. Return to full arm extension. Diverging path allows deeper mid-back contraction.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s5',  brand:'Life Fitness', name:'Insignia Shoulder Press', category:'Machine', targetArea:'Deltoids, Trapezius, Triceps', minWeight:'10', maxWeight:'200', instructions:'Handles at shoulder level. Press overhead through converging arc. Keep core braced. Lower slowly. Shoulders more injury-prone than other joints — use controlled weight.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s6',  brand:'Life Fitness', name:'Insignia Pec Fly / Rear Delt', category:'Machine', targetArea:'Pectoralis (fly), Posterior Deltoids, Rhomboids (rear delt)', minWeight:'10', maxWeight:'200', instructions:'Dual-function. Fly: arms sweep together in front. Rear delt: push arms back behind body plane. Adjust arm pad for each mode. Full stretch in fly; full squeeze in rear delt.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s7',  brand:'Life Fitness', name:'Insignia Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'10', maxWeight:'400', instructions:'Release safety handles. Lower to 90° knee bend. Press back to near-lockout. High+wide foot position = glutes. Low+narrow = quads. Never fully lock knees under heavy load.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'lf_s8',  brand:'Life Fitness', name:'Insignia Leg Extension', category:'Machine', targetArea:'Quadriceps (all 4 heads)', minWeight:'10', maxWeight:'200', instructions:'Align knees with machine pivot. Extend to full lockout, hold 1 second. Lower slowly. Single-leg option for imbalance correction. Do not let stack slam back.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'lf_s9',  brand:'Life Fitness', name:'Insignia Seated Leg Curl', category:'Machine', targetArea:'Hamstrings', minWeight:'10', maxWeight:'200', instructions:'Lap pad secures thighs. Curl roller toward seat. Squeeze hard at bottom. Return slowly — eccentric equally important. Plantarflex feet to increase gastrocnemius recruitment.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'lf_s10', brand:'Life Fitness', name:'Insignia Hip Abductor/Adductor', category:'Machine', targetArea:'Hip Abductors (outer thigh), Hip Adductors (inner thigh)', minWeight:'10', maxWeight:'200', instructions:'Select mode. Move through full ROM without momentum. Excellent for gluteus medius development and hip stability. Slow controlled reps — no bouncing at end range.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'lf_s11', brand:'Life Fitness', name:'Insignia Abdominal Crunch', category:'Machine', targetArea:'Rectus Abdominis, Obliques', minWeight:'5', maxWeight:'200', instructions:'Position elbow pads at chest height. Contract abs to crunch torso toward knees — initiate from abs, not arms. Hold peak 1 second. Return under control.', image:'https://images.unsplash.com/photo-1571019614242-c5c5adee9f50?q=80&w=1000' },
  { id:'lf_s12', brand:'Life Fitness', name:'Insignia Lower Back Extension', category:'Machine', targetArea:'Erector Spinae, Multifidus, Glutes', minWeight:'5', maxWeight:'200', instructions:'Ankles under foot pads, pad across upper thighs. Extend torso back to full extension, squeeze glutes and erectors at top. Return forward with control. Do not hyperextend or jerk.', image:'https://images.unsplash.com/photo-1571019614242-c5c5adee9f50?q=80&w=1000' },
  { id:'lf_s13', brand:'Life Fitness', name:'Insignia Bicep Curl', category:'Machine', targetArea:'Biceps Brachii, Brachialis, Brachioradialis', minWeight:'5', maxWeight:'150', instructions:'Rest upper arms on angled pad. Curl handles toward shoulders through full ROM. Lower slowly to full extension. Preacher pad isolates biceps by preventing shoulder swing.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s14', brand:'Life Fitness', name:'Insignia Tricep Extension', category:'Machine', targetArea:'Triceps Brachii (all three heads)', minWeight:'5', maxWeight:'150', instructions:'Grip handles at head level. Press to full extension, squeezing triceps at lockout. Return slowly. Keep upper arms stationary — movement at elbow only.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_s15', brand:'Life Fitness', name:'Dual Adjustable Pulley (DAP)', category:'Cable', targetArea:'Full Body – Any Cable Exercise', minWeight:'5', maxWeight:'390', instructions:'Two independently adjustable carriages high to low. Each stack works separately for full unilateral capability. Use for cable flyes, face pulls, chops, single-arm rows. Best all-around cable machine.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // LIFE FITNESS — Axiom Series (Compact Selectorized)
  // ═══════════════════════════════════════════════════════════════
  { id:'lf_ax1', brand:'Life Fitness', name:'Axiom Chest Press', category:'Machine', targetArea:'Chest, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'200', instructions:'Compact selectorized chest press for smaller facilities. Single-function design. Full ROM press with controlled return. Space-efficient for hotel gyms and boutique studios.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_ax2', brand:'Life Fitness', name:'Axiom Lat Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Biceps', minWeight:'10', maxWeight:'200', instructions:'Compact lat pulldown with knee pad. Grip overhand. Pull bar to upper chest. Small footprint ideal for space-limited facilities.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'lf_ax3', brand:'Life Fitness', name:'Axiom Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'10', maxWeight:'300', instructions:'Compact selectorized leg press. Adjust back pad angle. Lower until knees at 90°. Press back. Alternative to plate-loaded for lighter users or facilities without a dedicated leg room.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // HAMMER STRENGTH — Plate-Loaded Full Line
  // ═══════════════════════════════════════════════════════════════
  { id:'hs_pl1',  brand:'Hammer Strength', name:'PL Iso-Lateral Flat Bench Press', category:'Machine', targetArea:'Pectoralis Major, Anterior Deltoids, Triceps', minWeight:'45', maxWeight:'900', instructions:'Load both arms equally. Each arm moves independently. Natural arc press path. Lower to chest level, press back to near-lockout. Corrects strength imbalances between sides.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectchest-press-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl2',  brand:'Hammer Strength', name:'PL Iso-Lateral Incline Press', category:'Machine', targetArea:'Upper Pectoralis, Anterior Deltoids, Triceps', minWeight:'45', maxWeight:'700', instructions:'Inclined seat targets upper chest. Independent arms provide natural press path. Great alternative to barbell incline with less rotator cuff stress.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectchest-press-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl3',  brand:'Hammer Strength', name:'PL Iso-Lateral Decline Press', category:'Machine', targetArea:'Lower Pectoralis, Triceps, Anterior Deltoids', minWeight:'45', maxWeight:'700', instructions:'Declined position targets lower chest and sternal fibers. Each arm independent. Press forward and downward along natural decline arc for complete chest development.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectchest-press-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl4',  brand:'Hammer Strength', name:'PL Iso-Lateral Shoulder Press', category:'Machine', targetArea:'Deltoids, Triceps, Upper Trapezius', minWeight:'45', maxWeight:'500', instructions:'Adjust seat so handles start at shoulder height. Press overhead. Keep core braced. Lower slowly — shoulders more injury-prone. Independent arms allow natural pressing motion.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-shoulder-press-charcoal-black-1000x1000_42906fad-d921-458f-ad61-564725d77fe4.jpg' },
  { id:'hs_pl5',  brand:'Hammer Strength', name:'PL Iso-Lateral High Row', category:'Machine', targetArea:'Latissimus Dorsi, Rear Deltoids, Rhomboids, Biceps', minWeight:'45', maxWeight:'700', instructions:'Kneel on knee pad facing machine. Pull elbows back and down. Upward-angled pull mimics pull-up mechanics. Independent arms correct left-right imbalances.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-lat-pulldown-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl6',  brand:'Hammer Strength', name:'PL Iso-Lateral Low Row', category:'Machine', targetArea:'Mid-Back, Latissimus Dorsi, Biceps', minWeight:'45', maxWeight:'700', instructions:'Chest against pad. Row elbows back past torso. Diverging motion path works mid-back differently than cable rows. Return to complete arm extension.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-seated-row-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl7',  brand:'Hammer Strength', name:'PL Iso-Lateral Lat Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Teres Major, Biceps', minWeight:'45', maxWeight:'600', instructions:'Thighs under knee pad. Wide overhand grip. Pull elbows down and in. Each arm independent. Do not limit ROM by stopping early — full lat stretch at top is essential.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-lat-pulldown-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl8',  brand:'Hammer Strength', name:'PL Iso-Lateral Pullover', category:'Machine', targetArea:'Latissimus Dorsi, Serratus Anterior, Chest', minWeight:'45', maxWeight:'400', instructions:'Arms start overhead. Pull handles forward and down in an arc to hip level. Isolates lat and serratus without bicep involvement. Keep elbows slightly bent throughout.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-lat-pulldown-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl9',  brand:'Hammer Strength', name:'PL Iso-Lateral Front Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Biceps, Rear Deltoids', minWeight:'45', maxWeight:'500', instructions:'Facing machine. Pull handles to chest in front of body. Front path puts lats in different mechanical position vs overhead pulldown — excellent variety for complete lat development.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-lat-pulldown-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl10', brand:'Hammer Strength', name:'PL Linear Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'118', maxWeight:'1200', instructions:'Load plates symmetrically. Push platform up to release safety locks. Lower until knees at 90°. Press back up. Wide stance = more glutes. Narrow = more quads. Never fully lock knees under heavy load.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectseated-leg-pressbase-black-black-1000x1000.jpg' },
  { id:'hs_pl11', brand:'Hammer Strength', name:'PL Hack Squat', category:'Machine', targetArea:'Quadriceps, Glutes, Hamstrings', minWeight:'45', maxWeight:'900', instructions:'Stand on platform, back against pad. Release safeties. Lower to 90°. Drive through full foot. Forward lean shifts emphasis to glutes; more upright targets quads. One of the best quad mass builders.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectseated-leg-pressbase-black-black-1000x1000.jpg' },
  { id:'hs_pl12', brand:'Hammer Strength', name:'PL Pendulum-X Squat', category:'Machine', targetArea:'Quadriceps, Glutes, Hamstrings', minWeight:'45', maxWeight:'800', instructions:'Patent-pending pendulum resistance provides consistent tension through full squat ROM. Load plates. Full squats — arc design allows deeper range without locking out resistance.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectseated-leg-pressbase-black-black-1000x1000.jpg' },
  { id:'hs_pl13', brand:'Hammer Strength', name:'PL Hip Extension / Belt Squat', category:'Machine', targetArea:'Glutes, Hamstrings, Quadriceps', minWeight:'45', maxWeight:'600', instructions:'Secure hip belt across pelvis. Stand on platform. Squat with controlled tempo. Drive hips forward to extension. Eliminates axial spine loading — excellent for athletes with back injuries needing leg volume.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selecthip-and-glutebase-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl14', brand:'Hammer Strength', name:'PL Lying Leg Curl', category:'Machine', targetArea:'Hamstrings, Gastrocnemius', minWeight:'45', maxWeight:'400', instructions:'Lie face down. Position ankle roller just above heel. Curl legs toward glutes through full ROM. Plantarflex feet at top for greater gastrocnemius involvement. Dorsiflexing isolates hamstrings only.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-leg-curl-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl15', brand:'Hammer Strength', name:'PL Standing Leg Curl', category:'Machine', targetArea:'Hamstrings, Gastrocnemius (unilateral)', minWeight:'45', maxWeight:'300', instructions:'Stand and position one ankle under roller. Curl leg toward glute unilaterally. Trains hamstring in hip-extended position — closer to sprinting mechanics. Great for hamstring injury rehab.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-leg-curl-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl16', brand:'Hammer Strength', name:'PL Super Fly', category:'Machine', targetArea:'Pectoralis Major, Anterior Deltoids', minWeight:'45', maxWeight:'400', instructions:'Flat-to-decline adjustable fly. Set angle for target zone. Extend arms wide, bring together in hugging motion. Full stretch at bottom essential. Squeeze chest hard at peak.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-select-pectoral-fly-rear-deltoid-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl17', brand:'Hammer Strength', name:'PL Seated Dip', category:'Machine', targetArea:'Triceps, Lower Chest, Anterior Deltoids', minWeight:'45', maxWeight:'500', instructions:'Grip handles and push to full elbow extension. Lean slightly forward for more chest emphasis; upright for more tricep focus. Lower slowly to full range.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-charcoal-black-1000x1000.jpg' },
  { id:'hs_pl18', brand:'Hammer Strength', name:'PL Ground Base Multi-Squat', category:'Machine', targetArea:'Quadriceps, Glutes, Hamstrings, Core', minWeight:'45', maxWeight:'700', instructions:'Ground-based free-form squat machine. Pivot allows natural bar path. Great for sport-specific squatting patterns not achievable in a traditional rack.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-lat-pulldown-charcoal-black-1000x1000.jpg' },

  // ═══════════════════════════════════════════════════════════════
  // HAMMER STRENGTH — Select Selectorized Full Line
  // ═══════════════════════════════════════════════════════════════
  { id:'hs_sel1',  brand:'Hammer Strength', name:'Select Chest Press', category:'Machine', targetArea:'Chest, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'280', instructions:'Handles at mid-chest. Press through full ROM. Kevlar belt drive for smooth quiet resistance. Built for high-volume commercial use.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectchest-press-charcoal-black-1000x1000.jpg' },
  { id:'hs_sel2',  brand:'Hammer Strength', name:'Select Lat Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Biceps, Rear Deltoids', minWeight:'10', maxWeight:'280', instructions:'Set knee pad. Wide overhand grip. Pull to upper chest. Return slowly to full extension. Remote-activated adjustments allow seat changes from seated position.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-lat-pulldown-charcoal-black-1000x1000.jpg' },
  { id:'hs_sel3',  brand:'Hammer Strength', name:'Select Seated Row', category:'Machine', targetArea:'Mid-Back, Rhomboids, Biceps', minWeight:'10', maxWeight:'280', instructions:'Chest against pad. Row handles back past torso. Return to full extension. Smooth Kevlar belt — one of the most reliable rows in commercial settings.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-seated-row-charcoal-black-1000x1000.jpg' },
  { id:'hs_sel4',  brand:'Hammer Strength', name:'Select Shoulder Press', category:'Machine', targetArea:'Deltoids, Triceps, Trapezius', minWeight:'10', maxWeight:'220', instructions:'Handles start at shoulder height. Press overhead. Remote adjustments from seated position. Keep back against pad throughout movement.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-shoulder-press-charcoal-black-1000x1000_42906fad-d921-458f-ad61-564725d77fe4.jpg' },
  { id:'hs_sel5',  brand:'Hammer Strength', name:'Select Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'10', maxWeight:'350', instructions:'Adjust back pad. Release safeties. Lower until knees at 90°. Press back. Foot position affects emphasis. Never fully lock knees. Smooth 200 lb weight stack.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectseated-leg-pressbase-black-black-1000x1000.jpg' },
  { id:'hs_sel6',  brand:'Hammer Strength', name:'Select Leg Extension', category:'Machine', targetArea:'Quadriceps', minWeight:'10', maxWeight:'200', instructions:'Adjust ankle roller and seat. Extend to full lockout. Squeeze quad at top. Lower with control. Single-leg option for imbalances.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-select-leg-extension-charcoal-black-1000x1000.jpg' },
  { id:'hs_sel7',  brand:'Hammer Strength', name:'Select Seated Leg Curl', category:'Machine', targetArea:'Hamstrings', minWeight:'10', maxWeight:'250', instructions:'Adjust lap pad and ankle roller. Curl toward seat. Squeeze at bottom. Return slowly. Do not let hips rise during movement.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectseated-leg-curlbase_charcoalframe_blackuph_1000x1000_142fbee1-487a-4f8d-b616-4b5f53d23d8b.jpg' },
  { id:'hs_sel8',  brand:'Hammer Strength', name:'Select Abdominal Crunch', category:'Machine', targetArea:'Rectus Abdominis, Obliques', minWeight:'5', maxWeight:'180', instructions:'Position elbow pads at chest. Contract abs to crunch — not pulling with arms. Hold peak 1 second. Return under control.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectabdominal-crunch-charcoal-black-1000x1000.jpg' },
  { id:'hs_sel9',  brand:'Hammer Strength', name:'Select Hip Abductor', category:'Machine', targetArea:'Hip Abductors, Gluteus Medius, TFL', minWeight:'10', maxWeight:'200', instructions:'Feet together. Push knees apart through full outer ROM. Excellent for glute medius development and hip stability. Slow controlled reps — no bouncing.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-hip-abduction-charcoal-black-1000x01000.jpg' },
  { id:'hs_sel10', brand:'Hammer Strength', name:'Select Hip Adductor', category:'Machine', targetArea:'Hip Adductors, Inner Thigh, Groin', minWeight:'10', maxWeight:'200', instructions:'Knees apart on pads. Squeeze knees together through full inner ROM. Important for groin health and medial quad stability.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-hip-adduction-charcoal-black-1000x01000.jpg' },

  // ═══════════════════════════════════════════════════════════════
  // HAMMER STRENGTH — MTS (Motion Technology Selectorized)
  // ═══════════════════════════════════════════════════════════════
  { id:'hs_mts1', brand:'Hammer Strength', name:'MTS Iso-Lateral Chest Press', category:'Machine', targetArea:'Pectoralis, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'280', instructions:'Independent weight stacks per arm — offset loads, alternating reps, or unilateral training possible. Offers the feel of plate-loaded with weight stack convenience.', image:'https://shop.lifefitness.com/cdn/shop/files/hammer-strength-selectchest-press-charcoal-black-1000x1000.jpg' },
  { id:'hs_mts2', brand:'Hammer Strength', name:'MTS Iso-Lateral Row', category:'Machine', targetArea:'Back, Biceps, Rear Deltoids', minWeight:'10', maxWeight:'280', instructions:'Independent weight stacks for each arm. Converging/diverging path mirrors plate-loaded row. Use both arms, alternating, or single-arm. Unique iso-lateral experience.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-seated-row-charcoal-black-1000x1000.jpg' },
  { id:'hs_mts3', brand:'Hammer Strength', name:'MTS Iso-Lateral Shoulder Press', category:'Machine', targetArea:'Deltoids, Triceps, Upper Trapezius', minWeight:'10', maxWeight:'250', instructions:'Independent weight stacks. Press with both, one, or with offset loads. Natural arcing press path in a selectorized body. Great for all levels.', image:'https://shop.lifefitness.com/cdn/shop/files/outlet-hammer-strength-select-shoulder-press-charcoal-black-1000x1000_42906fad-d921-458f-ad61-564725d77fe4.jpg' },

  // ═══════════════════════════════════════════════════════════════
  // HAMMER STRENGTH — Free Weight & Racks
  // ═══════════════════════════════════════════════════════════════
  { id:'hs_fw1', brand:'Hammer Strength', name:'HD Athletic NX Power Rack', category:'Free Weight', targetArea:'Full Body – Squat, Bench, OHP, Deadlift, Pull-ups', minWeight:'0', maxWeight:'1000', instructions:'Full commercial power rack with multi-grip pull-up bar. Set J-hooks and safety arms before every session. Available in full and half-rack. Ideal for athlete training rooms.', image:'https://shop.lifefitness.com/cdn/shop/products/hammer-strength-athletic-NX-half-rack-charcoal-ecomm-1000x1000-2.jpg' },
  { id:'hs_fw2', brand:'Hammer Strength', name:'Adjustable Multi-Bench', category:'Free Weight', targetArea:'Chest, Shoulders, Triceps, Back', minWeight:'0', maxWeight:'600', instructions:'Multiple incline positions from flat to 90°. Wide base for stability. Use for dumbbell press, incline press, step-ups, and supported rows. Always lock angle before loading.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Weight%20Benches/Adjustable%20:%20Incline%20Benches/RF0935/RF0935-MG-Black-TH_vj8tsi.png' },
  { id:'hs_fw3', brand:'Hammer Strength', name:'Adjustable Decline Bench', category:'Free Weight', targetArea:'Lower Chest, Core Stability', minWeight:'0', maxWeight:'500', instructions:'Adjust for precise decline positioning. Anchor legs under roller pads. Wide base prevents tipping under heavy dumbbell loads.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Strength%20Equipment/Strength%20Training/Weight%20Benches/Adjustable%20:%20Incline%20Benches/RF0935/RF0935-MG-Black-TH_vj8tsi.png' },
  { id:'hs_fw4', brand:'Hammer Strength', name:'PRO 100 Adjustable Dumbbells', category:'Free Weight', targetArea:'Full Body', minWeight:'5', maxWeight:'100', instructions:'Dial selector adjusts in 5 lb increments. Always set weight before lifting. Return to cradle before adjusting. Replaces a full dumbbell rack in smaller training settings.', image:'https://assets.roguefitness.com/f_auto,q_auto,c_fill,g_center,w_800,h_600,b_rgb:f8f8f8/catalog/Conditioning/Strength%20Equipment/Kettlebells/USC001-PC/USC001-PC-TH_fyhrze.png' },

  // ═══════════════════════════════════════════════════════════════
  // PRECOR — Full Line
  // ═══════════════════════════════════════════════════════════════
  { id:'pr_1',  brand:'Precor', name:'TRM 885 Commercial Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Ground Effects® cushioning reduces injury risk. P82 touchscreen. Maximum 16 mph, 15% incline. Use incline intervals for calorie burn without high-speed impact.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'pr_2',  brand:'Precor', name:'EFX 885 Elliptical Cross-Trainer', category:'Cardio', targetArea:'Full Body, Glutes, Legs, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Adjustable stride (17-26"). Incline 0-40° dramatically shifts muscle emphasis. Moving handlebars engage upper body. 20 resistance levels.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'pr_3',  brand:'Precor', name:'AMT 885 Adaptive Motion Trainer', category:'Cardio', targetArea:'Full Body, Glutes, Legs, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Adapts to any stride length (0-36") automatically. Short steps = stair-climbing; long strides = running. Users transition between movements mid-session without stopping.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'pr_4',  brand:'Precor', name:'UBK 885 Upright Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Eddy current resistance requires zero maintenance. 25 resistance levels. Use CrossRamp programs for interval sessions. Upper handlebars for light upper body engagement.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'pr_5',  brand:'Precor', name:'RBK 885 Recumbent Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Step-through frame for easy access. Adjust seat so leg is near full extension at bottom stroke. Great for members with mobility limitations or lower back sensitivity.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'pr_6',  brand:'Precor', name:'Arc Trainer 750A', category:'Cardio', targetArea:'Glutes, Hamstrings, Calves, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Arc motion significantly activates posterior chain. Incline 0-18°; resistance 1-100. Forward lean at incline maximizes glutes. Proven higher calorie burn per step vs standard ellipticals.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'pr_7',  brand:'Precor', name:'Discovery Chest Press', category:'Machine', targetArea:'Chest, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'280', instructions:'Converging press path matches natural motion. Pop-pin weight selection. Diverging return creates unique stretch. Excellent starting point for new members.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'pr_8',  brand:'Precor', name:'Discovery Lat Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Biceps, Rear Deltoids', minWeight:'10', maxWeight:'280', instructions:'Set knee pads snugly. Wide overhand grip. Pull to upper chest. Diverging pulldown path puts lats in strong position for full range.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'pr_9',  brand:'Precor', name:'Discovery Seated Row', category:'Machine', targetArea:'Mid-Back, Latissimus Dorsi, Biceps', minWeight:'10', maxWeight:'280', instructions:'Chest pad stabilizes torso. Row elbows back past torso. Diverging path allows deeper contraction. Return to full arm extension.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'pr_10', brand:'Precor', name:'Discovery Shoulder Press', category:'Machine', targetArea:'Deltoids, Triceps, Trapezius', minWeight:'10', maxWeight:'250', instructions:'Converging arc press. Handles start at shoulder level. Press overhead. Remote-activated seat adjustment. Ergonomic grips reduce wrist strain.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'pr_11', brand:'Precor', name:'Discovery Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'10', maxWeight:'350', instructions:'Adjustable back pad. Release safeties. Lower until knees at 90°. Press back. Foot position changes muscle emphasis.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'pr_12', brand:'Precor', name:'Discovery Leg Extension', category:'Machine', targetArea:'Quadriceps', minWeight:'10', maxWeight:'220', instructions:'Align knee with pivot. Extend to lockout. Squeeze quad at top. Lower with control. Single-leg option available.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'pr_13', brand:'Precor', name:'Discovery Leg Curl', category:'Machine', targetArea:'Hamstrings, Gastrocnemius', minWeight:'10', maxWeight:'220', instructions:'Position ankle roller above heel. Curl through full ROM. Eccentric equally important. Consistent cable resistance throughout.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'pr_14', brand:'Precor', name:'FTS Glide Functional Training System', category:'Cable', targetArea:'Full Body – Functional Movement Patterns', minWeight:'5', maxWeight:'200', instructions:'Dual cable with horizontal sliding carriage that follows natural movement. Adjust carriage and cable height. Allows 3D movement patterns impossible on fixed cable machines.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'pr_15', brand:'Precor', name:'Plate-Loaded Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'45', maxWeight:'1000', instructions:'Load plates symmetrically. Adjust back pad. Release safeties. Lower until 90°. Press back up. One of the heaviest-loaded exercises in any routine.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'pr_16', brand:'Precor', name:'Glutebuilder Machine', category:'Machine', targetArea:'Glutes, Hamstrings', minWeight:'45', maxWeight:'600', instructions:'Secure hip belt. Position feet flat on angled platform. Drive hips upward to full extension. Adjustable pad and foot platform. Excellent for glute-dominant hip thrust pattern.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // MATRIX FITNESS
  // ═══════════════════════════════════════════════════════════════
  { id:'mx_1', brand:'Matrix Fitness', name:'T75 Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'MXS suspension cushioning. XIR touchscreen. Up to 12% incline, 12 mph. Bluetooth app integration. Great for mixed-ability gym populations.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'mx_2', brand:'Matrix Fitness', name:'E50 Elliptical', category:'Cardio', targetArea:'Full Body, Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Adjustable stride (18-22"). 20 incline levels, 20 resistance levels. XIR touchscreen. Moving handlebars for full body engagement.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'mx_3', brand:'Matrix Fitness', name:'C50 Upright Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Adjust seat for slight knee bend. 30 resistance levels. XIR console with virtual training. Smooth eddy-current resistance — no maintenance required.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'mx_4', brand:'Matrix Fitness', name:'R50 Recumbent Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Step-through frame. One-touch seat adjustment. 30 resistance levels. XIR touchscreen entertainment. Low-impact for seniors and rehab.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'mx_5', brand:'Matrix Fitness', name:'ClimbMill Stairclimber', category:'Cardio', targetArea:'Glutes, Quadriceps, Calves, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Stand upright, lightly hold rails. Select speed via touchscreen. Full steps target glutes; short steps maximize cardio demand. Highest calorie burn per minute of most cardio machines.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'mx_6', brand:'Matrix Fitness', name:'Connexus Functional Training Unit', category:'Cable', targetArea:'Full Body — Functional and Athletic Movement', minWeight:'5', maxWeight:'300', instructions:'Multi-cable functional training rig. Multiple anchor points at varying heights. Great for small group training, circuit work, and sport-specific movement patterns.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'mx_7', brand:'Matrix Fitness', name:'G1 Selectorized Strength Circuit', category:'Machine', targetArea:'Full Body – Multiple Stations', minWeight:'10', maxWeight:'280', instructions:'Complete circuit includes chest press, lat pulldown, shoulder press, leg press, leg extension, leg curl, and seated row. Converging/diverging paths for natural motion. Pop-pin weight selection.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'mx_8', brand:'Matrix Fitness', name:'Ultra Series Indoor Cycling Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Power meter tracks watts. Used for structured power-based training. Compatible with Peloton App and other cycling platforms via Bluetooth. Adjustable seat and handlebars.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // PELOTON
  // ═══════════════════════════════════════════════════════════════
  { id:'pt_1', brand:'Peloton', name:'Peloton Bike+', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'297', instructions:'Clip in Look Delta shoes. Seat height to hip level standing beside bike. Auto-Follow resistance adjusts automatically during classes on the 23.8" rotating touchscreen. 100 resistance levels.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'pt_2', brand:'Peloton', name:'Peloton Tread+', category:'Cardio', targetArea:'Legs, Glutes, Core, Cardiovascular', minWeight:'0', maxWeight:'300', instructions:'Attach safety key. Rolling dials adjust speed and incline instantly during class. 32" touchscreen with live and on-demand classes. Slat belt provides cushioning and natural foot feel.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'pt_3', brand:'Peloton', name:'Peloton Row', category:'Cardio', targetArea:'Full Body, Back, Legs, Core, Cardiovascular', minWeight:'0', maxWeight:'300', instructions:'Strap feet in. Drive legs, lean back, pull to lower ribs. Form Assist provides real-time visual feedback. Target Pace indicator guides effort. Folds upright for storage.', image:'https://images.unsplash.com/photo-1596357395104-caede1b6ab3d?q=80&w=1000' },
  { id:'pt_4', brand:'Peloton', name:'Peloton Guide', category:'Machine', targetArea:'Full Body – Strength Training', minWeight:'0', maxWeight:'0', instructions:'Camera-based strength training device. Tracks reps automatically and detects muscle groups. Use with dumbbells and bodyweight. Access Peloton strength, bootcamp, sculpt, barre, and yoga classes.', image:'https://images.unsplash.com/photo-1571019614242-c5c5adee9f50?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // CONCEPT2
  // ═══════════════════════════════════════════════════════════════
  { id:'c2_1', brand:'Concept2', name:'RowErg Model D (PM5)', category:'Cardio', targetArea:'Legs, Back, Core, Arms, Cardiovascular', minWeight:'0', maxWeight:'500', instructions:'Strap feet in. Drive legs first, hinge hips back, pull to lower chest. Recovery: arms out, hinge forward, knees bend. Damper 3-5 typical. Track split time per 500m on PM5.', image:'https://images.unsplash.com/photo-1596357395104-caede1b6ab3d?q=80&w=1000' },
  { id:'c2_2', brand:'Concept2', name:'BikeErg', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'500', instructions:'Adjust seat and handlebars. Damper controls air resistance feel. PM5 monitor tracks watts and calories. Watt-based training most effective — target power zones not speed.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'c2_3', brand:'Concept2', name:'SkiErg', category:'Cardio', targetArea:'Upper Body, Lats, Core, Triceps, Cardiovascular', minWeight:'0', maxWeight:'0', instructions:'Stand facing unit. Grip handles overhead. Pull both handles down diagonally past hips. Drive with core and lats. Alternate arms for cross-country ski pattern.', image:'https://images.unsplash.com/photo-1594737625785-a6cb20f5f80b?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // STAIRMASTER
  // ═══════════════════════════════════════════════════════════════
  { id:'sm_1', brand:'StairMaster', name:'Gauntlet Stepmill 10G', category:'Cardio', targetArea:'Glutes, Quadriceps, Hamstrings, Calves, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Step on carefully. Maintain upright posture — hands lightly on rails for balance only. Full steps target glutes; shorter steps increase cardiovascular demand. 16 levels from 24-162 steps/min.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'sm_2', brand:'StairMaster', name:'8 Series Stepper', category:'Cardio', targetArea:'Glutes, Quadriceps, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Independent pedal movement simulates stair-climbing. Grip rails lightly for balance only — NOT for support. Avoid hanging on rails which reduces calorie burn.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'sm_3', brand:'StairMaster', name:'HIITMill X Self-Powered Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Core, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Curved self-powered treadmill. Speed controlled entirely by effort — no motor. Sprint at full effort, reduce pace naturally. Promotes midfoot strike and natural gait. Excellent for HIIT sprint intervals.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'sm_4', brand:'StairMaster', name:'HIIT UBE Upper Body Ergometer', category:'Cardio', targetArea:'Shoulders, Chest, Back, Core, Cardiovascular', minWeight:'0', maxWeight:'0', instructions:'Sit or stand facing crank unit. Grip handles and turn using arms. Forward cranking targets chest/anterior shoulders; backward targets back/posterior shoulders. Great for lower body injury recovery.', image:'https://images.unsplash.com/photo-1594737625785-a6cb20f5f80b?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // TECHNOGYM
  // ═══════════════════════════════════════════════════════════════
  { id:'tg_1', brand:'Technogym', name:'Skillrun Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Core, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Dual mode: SKILL (self-powered, sprint/sled simulation) and RUN (motorized). Parabolic curved surface promotes natural gait. Connect to Technogym App. SKILL mode enables resisted running.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'tg_2', brand:'Technogym', name:'Run Personal Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Premium club treadmill with Biocircuit integration. FlexMotion cushioning. Up to 20 km/h, 20% incline. Connect personal Technogym App for continuous progress tracking.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'tg_3', brand:'Technogym', name:'Excite Live Bike', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'25 resistance levels. Outdoor route simulation available. Connect to Technogym App. RIDE mode simulates real-world cycling. Ergonomic seat with multi-position handlebars.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'tg_4', brand:'Technogym', name:'Artis Elliptical', category:'Cardio', targetArea:'Full Body, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'10 incline levels. Console streams Technogym TV. Forward/reverse pedaling for varied muscle engagement. Natural stride reduces joint impact.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'tg_5', brand:'Technogym', name:'Pure Strength Plate-Loaded Line', category:'Machine', targetArea:'Full Body – Multiple Machines Available', minWeight:'45', maxWeight:'800', instructions:'Full plate-loaded line including chest press, shoulder press, lat pulldown, seated row, leg press, hack squat, and leg curl. Biplanar movement paths follow natural joint kinematics.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'tg_6', brand:'Technogym', name:'Pure Strength Cable Tower', category:'Cable', targetArea:'Full Body', minWeight:'5', maxWeight:'300', instructions:'Dual cable pulley with height-adjustable carriages. Smooth ball-bearing pulleys. Pairs with Pure Strength plate-loaded line for cohesive design. Full cable exercise library with appropriate attachments.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'tg_7', brand:'Technogym', name:'Kinesis Personal Cable Machine', category:'Cable', targetArea:'Full Body – 3D Movement Patterns', minWeight:'5', maxWeight:'200', instructions:'360° cable movement. Cables pivot in any direction for 3D functional movement. Used in Olympic training programs. Only machine allowing complete freedom of movement for rehab and sport-specific training.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
  { id:'tg_8', brand:'Technogym', name:'SKILLROW Rowing Machine', category:'Cardio', targetArea:'Full Body, Back, Legs, Core, Cardiovascular', minWeight:'0', maxWeight:'0', instructions:'First connected rower combining gaming and elite coaching. RACE mode for competitive training. ARUSH feedback coaches technique in real-time. Electromagnetic resistance with water-resistance feel.', image:'https://images.unsplash.com/photo-1596357395104-caede1b6ab3d?q=80&w=1000' },
  { id:'tg_9', brand:'Technogym', name:'Omnia Multi-Functional Trainer', category:'Cable', targetArea:'Full Body – Circuit and Functional Training', minWeight:'0', maxWeight:'0', instructions:'Combines cables, pull-up bars, dip stations, landmine, and storage in one unit. Ideal for small group training. Compact footprint with maximum training variety. Up to 8 users simultaneously.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },

  // ═══════════════════════════════════════════════════════════════
  // CYBEX
  // ═══════════════════════════════════════════════════════════════
  { id:'cy_1',  brand:'Cybex', name:'Arc Trainer 750A', category:'Cardio', targetArea:'Glutes, Hamstrings, Calves, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Arc motion activates posterior chain. Incline 0-18°; resistance 1-100. Forward lean at incline maximizes glutes. Proven higher calorie burn per step vs standard ellipticals with less knee stress.', image:'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=1000' },
  { id:'cy_2',  brand:'Cybex', name:'770T Commercial Treadmill', category:'Cardio', targetArea:'Legs, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Speed up to 16 mph, incline 0-15%. SpaceSaver shock absorption reduces impact. Rapid incline changes during interval sessions. SPARC program for time-efficient HIIT training.', image:'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000' },
  { id:'cy_3',  brand:'Cybex', name:'750C Upright Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'350', instructions:'Adjust seat for slight knee bend. 25 resistance levels. Upper body handlebars. Integrated fan. Touchscreen console with multiple program options.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'cy_4',  brand:'Cybex', name:'750R Recumbent Bike', category:'Cardio', targetArea:'Quadriceps, Hamstrings, Glutes, Cardiovascular', minWeight:'0', maxWeight:'400', instructions:'Recumbent position with back support. Step-through frame. 25 resistance levels. Open-space seat. Great for rehabilitation settings and senior fitness facilities.', image:'https://images.unsplash.com/photo-1570829460005-c840387bb1ea?q=80&w=1000' },
  { id:'cy_5',  brand:'Cybex', name:'VR3 Chest Press', category:'Machine', targetArea:'Chest, Anterior Deltoids, Triceps', minWeight:'10', maxWeight:'280', instructions:'Kevlar belt drive for ultra-smooth operation. Press path follows natural shoulder arc. Adjustable seat. Built for abusive commercial environments. One of the smoothest chest press machines available.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'cy_6',  brand:'Cybex', name:'VR3 Lat Pulldown', category:'Machine', targetArea:'Latissimus Dorsi, Biceps, Rear Deltoids', minWeight:'10', maxWeight:'280', instructions:'Diverging pulldown path. Set knee pad. Overhand grip. Pull to upper chest. Dual-direction cable system for smooth resistance throughout full ROM.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'cy_7',  brand:'Cybex', name:'VR3 Seated Row', category:'Machine', targetArea:'Mid-Back, Rhomboids, Biceps', minWeight:'10', maxWeight:'280', instructions:'Chest pad stabilizes torso. Row elbows back past torso. Consistent Kevlar resistance throughout movement. Premium construction built for decades of commercial use.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'cy_8',  brand:'Cybex', name:'VR3 Shoulder Press', category:'Machine', targetArea:'Deltoids, Triceps, Trapezius', minWeight:'10', maxWeight:'250', instructions:'Handles at shoulder height. Press through converging arc overhead. Smooth Kevlar resistance. Designed to minimize shoulder impingement risk during overhead pressing.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'cy_9',  brand:'Cybex', name:'VR3 Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'10', maxWeight:'400', instructions:'Converging press path mimics natural squat mechanics. Lower until knees at 90°. Press through full ROM. Foot placement changes emphasis. Smooth Kevlar drive.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'cy_10', brand:'Cybex', name:'VR3 Leg Extension', category:'Machine', targetArea:'Quadriceps', minWeight:'10', maxWeight:'220', instructions:'Align knee with pivot. Extend to full lockout. Squeeze quad at top. Return slowly. Consistent resistance from beginning to end due to Cybex patented cam design.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'cy_11', brand:'Cybex', name:'VR3 Leg Curl', category:'Machine', targetArea:'Hamstrings, Gastrocnemius', minWeight:'10', maxWeight:'220', instructions:'Position ankle roller above heel. Curl through full ROM. Eccentric equally important. Consistent cable resistance — no dead zones at top or bottom of curl.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'cy_12', brand:'Cybex', name:'VR3 Pec Fly / Rear Delt', category:'Machine', targetArea:'Pectoralis (fly), Posterior Deltoids (rear delt)', minWeight:'10', maxWeight:'200', instructions:'Dual-function. Fly: arms sweep together in front. Rear delt: push arms back behind body plane. Adjust arm pad for each mode. Full stretch in fly; full squeeze in rear delt.', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000' },
  { id:'cy_13', brand:'Cybex', name:'45° Linear Leg Press', category:'Machine', targetArea:'Quadriceps, Hamstrings, Glutes', minWeight:'10', maxWeight:'1000', instructions:'Load plates on rails. Release safeties. Lower until knees at 90°. Drive through heels to press back up. Wide stance = more glutes; narrow = more quads.', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000' },
  { id:'cy_14', brand:'Cybex', name:'Total Access Cable Column', category:'Cable', targetArea:'Full Body – Any Cable Exercise', minWeight:'5', maxWeight:'300', instructions:'Full-height adjustable single cable column. Place anywhere as a standalone station. Pairs with handle kit for complete cable exercise library. Great for adding cable work to strength areas.', image:'https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=1000' },
];
