// Seed data — used once on first launch when the gyms table is empty.
// After the initial seed, gyms are read/written from Supabase.

// Two demo gyms with logins. ownerID/password are intentionally weak (demo only).
export const INITIAL_OWNER_DATA = [
  {
    id: '1',
    ownerID: 'owner',
    password: '123',
    gymName: 'Iron Paradise',
    name: 'Iron Paradise',
    location: '123 Muscle Way, Columbus, OH',
    lat: 39.9650,
    lon: -83.0010,
    phone: '(555) 123-4567',
    website: 'https://www.ironparadise.com',
    pricing: '$59.99 / month',
    monthlyPrice: 59.99,
    dayPassPrice: 20.00,
    openHour: 5,
    closeHour: 23,
    hoursDisplay: 'Mon–Fri 5AM–11PM, Sat–Sun 7AM–9PM',
    plan: 'pro',
    featured: true,
    referralCode: 'IRONPRO24',
    referralCount: 7,
    referralRevenue: 525.00,
    totalPassRevenue: 3840.00,
    platformFeesPaid: 460.80,
    monthlyPassSales: 192,
    passes: [
      { id: 'p1', label: 'Single Day Pass',       price: 20.00,  type: 'TIME',  value: 1  },
      { id: 'p2', label: '1-Week Trial',          price: 45.00,  type: 'TIME',  value: 7  },
      { id: 'p3', label: '10-Class Punch Card',   price: 150.00, type: 'PUNCH', value: 10 },
    ],
    classes: ['HIIT', 'Boxing'],
    trainers: [
      { id: 't1', name: 'Arnold S.', fee: 75, bio: 'Specializes in bodybuilding and powerlifting.' },
    ],
    description: 'The ultimate hardcore training facility.',
    gymReviews: [
      { id: 'gr1', userId: 'admin1', username: 'admin', rating: 5, text: 'Amazing equipment selection and always clean!', date: new Date(Date.now() - 86400000 * 3).toISOString() },
    ],
    equipment: [
      { id: 'e1', name: 'Hammer Strength Squat Rack', category: 'Free Weight', instructions: 'Ensure safety bars are set to hip height.', targetArea: 'Quadriceps, Gluteus Maximus, Core', minWeight: '45', maxWeight: '800', mfgDate: '1/15/2023', serviceDate: '4/1/2026', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000', muscleDiagram: '', videoThumbnail: '', reviews: [] },
    ],
  },
  {
    id: '2',
    ownerID: 'zenowner',
    password: '123',
    gymName: 'Zen Wellness Studio',
    name: 'Zen Wellness Studio',
    location: '99 Lotus Lane, Dublin, OH',
    lat: 40.0992,
    lon: -83.1141,
    phone: '(555) 987-6543',
    website: 'https://www.zenwellness.com',
    pricing: '$29.99 / month',
    monthlyPrice: 29.99,
    dayPassPrice: 15.00,
    openHour: 6,
    closeHour: 21,
    hoursDisplay: 'Daily 6AM–9PM',
    plan: 'basic',
    featured: false,
    referralCode: 'ZEN2024',
    referralCount: 2,
    referralRevenue: 100.00,
    totalPassRevenue: 620.00,
    platformFeesPaid: 74.40,
    monthlyPassSales: 31,
    passes: [],
    classes: ['Yoga', 'Pilates', 'Cycling'],
    trainers: [],
    description: 'A calming space focused on flexibility, core strength, and cardiovascular health.',
    gymReviews: [],
    equipment: [],
  },
];

// Real-world gym data (researched, within ~50 miles of Westerville, OH).
// All public info. Owner credentials blank — admins claim by contacting support.
export const REAL_GYMS_DATA = [
  {
    id: 'rg_fitness19_westerville', ownerID: 'rg_fitness19', password: '',
    gymName: 'Fitness 19 Westerville', name: 'Fitness 19 Westerville',
    location: '85 W Schrock Rd, Westerville, OH 43081',
    lat: 40.1058, lon: -82.9070,
    phone: '(614) 899-1919',
    website: 'https://www.fitness19.com/centers/westerville/',
    pricing: 'From $19.99/month', monthlyPrice: 19.99, dayPassPrice: 0,
    openHour: 0, closeHour: 0,
    hoursDisplay: 'Open 24/7',
    passes: [], classes: ['HIIT', 'Group Fitness'], trainers: [], gymReviews: [],
    description: 'Affordable neighborhood fitness center with high-tech cardio equipment, free weights, circuit training, TRX suspension training, and kettlebell areas. Personal training and group fitness classes included. Friendly local staff, month-to-month memberships, no hefty signup fees. Open 24 hours.',
    equipment: [
      { id: 'rg_f19_e1', name: 'Cardio Equipment (Treadmills, Bikes, Ellipticals)', category: 'Cardio', targetArea: 'Cardiovascular System, Legs', minWeight: '0', maxWeight: '0', instructions: 'Adjust settings to desired speed/resistance. Attach safety clip if available. Maintain upright posture.', reviews: [] },
      { id: 'rg_f19_e2', name: 'Free Weight Area', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '100', instructions: 'Select appropriate dumbbells or barbells. Use mirrors for form checks. Return weights to rack after use.', reviews: [] },
      { id: 'rg_f19_e3', name: 'Circuit Training Stations', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '200', instructions: 'Move station to station with short rest intervals. Adjust pin to appropriate weight before starting.', reviews: [] },
      { id: 'rg_f19_e4', name: 'TRX Suspension Trainer', category: 'Cable', targetArea: 'Core, Full Body', minWeight: '0', maxWeight: '0', instructions: 'Adjust foot position for desired difficulty — further from anchor = harder. Keep core tight throughout all movements.', reviews: [] },
      { id: 'rg_f19_e5', name: 'Kettlebell Rack', category: 'Free Weight', targetArea: 'Full Body, Core', minWeight: '10', maxWeight: '70', instructions: 'Start with lighter bells to learn swing mechanics. Drive movement with hips, not arms.', reviews: [] },
    ],
  },
  {
    id: 'rg_planet_huber', ownerID: 'rg_planet1', password: '',
    gymName: 'Planet Fitness – Huber Village', name: 'Planet Fitness – Huber Village',
    location: '87 Huber Village Blvd, Westerville, OH 43081',
    lat: 40.1230, lon: -82.9054,
    phone: '(614) 310-4544',
    website: 'https://www.planetfitness.com/gyms/westerville-westerville-plaza-huber-village-blvd-oh',
    pricing: 'Classic $15/mo · Black Card $25/mo', monthlyPrice: 15.00, dayPassPrice: 0,
    openHour: 5, closeHour: 0,
    hoursDisplay: 'Mon 5AM–Midnight · Tue–Thu 24hrs · Fri closes 10PM · Sat–Sun 7AM–7PM',
    passes: [], classes: ['Group Fitness'], trainers: [], gymReviews: [],
    description: 'Judgment Free Zone® with extensive cardio and strength machines. Free fitness training included with all memberships. Black Card members bring a guest for free and access all PF locations worldwide. No commitment options available. Clean, welcoming environment for all fitness levels.',
    equipment: [
      { id: 'rg_pf1_e1', name: 'Cardio Zone (Treadmills, Ellipticals, Bikes, Stairclimbers)', category: 'Cardio', targetArea: 'Cardiovascular System, Legs', minWeight: '0', maxWeight: '0', instructions: 'Press Quick Start or enter your desired program. Clip safety cord to clothing.', reviews: [] },
      { id: 'rg_pf1_e2', name: 'Strength Machine Circuit', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '250', instructions: 'Use the guided 30-minute Express Circuit or work at your own pace. Adjust pin or selectorized weight before each set.', reviews: [] },
      { id: 'rg_pf1_e3', name: 'Free Weight Area (Dumbbells & Barbells)', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '80', instructions: 'Dumbbell range available. Benches on floor. Use collars on barbells.', reviews: [] },
    ],
  },
  {
    id: 'rg_planet_polaris', ownerID: 'rg_planet2', password: '',
    gymName: 'Planet Fitness – Polaris Pkwy', name: 'Planet Fitness – Polaris Pkwy',
    location: '865 Polaris Pkwy, Westerville, OH 43082',
    lat: 40.1561, lon: -82.9981,
    phone: '(614) 300-0000',
    website: 'https://www.planetfitness.com/gyms/westerville-westar-center-polaris-parkway-oh/',
    pricing: 'Classic $15/mo · Black Card $25/mo', monthlyPrice: 15.00, dayPassPrice: 0,
    openHour: 5, closeHour: 0,
    hoursDisplay: 'Mon 5AM–Midnight · Tue–Thu 24hrs · Fri closes 10PM · Sat–Sun 7AM–7PM',
    passes: [], classes: ['Group Fitness'], trainers: [], gymReviews: [],
    description: 'Second Westerville-area Planet Fitness location near Polaris Mall. Judgment Free Zone® with extensive cardio and strength machines, free fitness training, and small group training sessions. Convenient access from Polaris area.',
    equipment: [
      { id: 'rg_pf2_e1', name: 'Cardio Zone', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Full range of treadmills, ellipticals, bikes and stairclimbers available.', reviews: [] },
      { id: 'rg_pf2_e2', name: 'Strength Machine Circuit', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '250', instructions: 'Guided circuit or open floor training available.', reviews: [] },
    ],
  },
  {
    id: 'rg_nextlevel_westerville', ownerID: 'rg_nextlevel', password: '',
    gymName: 'Next Level Fitness & Training', name: 'Next Level Fitness & Training',
    location: '1220 County Line Rd, Westerville, OH 43081',
    lat: 40.1178, lon: -82.9178,
    phone: '(614) 776-4570',
    website: 'https://www.nextlevelfitness1.com/',
    pricing: 'Contact for rates · Military/Student discounts available', monthlyPrice: 35.00, dayPassPrice: 0,
    openHour: 5, closeHour: 22,
    hoursDisplay: 'Mon–Thu 5AM–10PM · Fri 5AM–9PM · Sat 7AM–7PM · Sun 8AM–6PM',
    passes: [], classes: ['Yoga', 'Cycling', 'Zumba', 'Group Fitness', 'HIIT'], trainers: [], gymReviews: [],
    description: 'Family-owned and operated since 2002. Full-service gym with group fitness studios, infrared saunas, showers, and lockers. 55+ weekly classes including Les Mills Group Fit, Yoga, Cycling, Barre, and Zumba. Silver Sneakers accepted. Kids Club available. Personal training from certified coaches. Military, first responder, and student discounts offered.',
    equipment: [
      { id: 'rg_nl_e1', name: 'Full Gym Floor (Machines & Free Weights)', category: 'Machine', targetArea: 'Full Body', minWeight: '5', maxWeight: '300', instructions: 'Comprehensive selection of machines and free weights for all fitness levels.', reviews: [] },
      { id: 'rg_nl_e2', name: 'Group Fitness Studio', category: 'Cardio', targetArea: 'Full Body, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'View the live class schedule and book your spot via the Mindbody app.', reviews: [] },
      { id: 'rg_nl_e3', name: 'Infrared Sauna', category: 'Machine', targetArea: 'Recovery, Full Body', minWeight: '0', maxWeight: '0', instructions: 'Sessions typically 20–30 minutes. Stay hydrated. Wipe down bench after use.', reviews: [] },
      { id: 'rg_nl_e4', name: 'Indoor Cycling Studio', category: 'Cardio', targetArea: 'Legs, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'Adjust seat height and handlebar position before class. Clip in shoes if using clip pedals.', reviews: [] },
    ],
  },
  {
    id: 'rg_fitclub_westerville', ownerID: 'rg_fitclub', password: '',
    gymName: 'Fit Club – CrossFit Westerville', name: 'Fit Club – CrossFit Westerville',
    location: '1220 County Line Rd, Corner Suite, Westerville, OH 43081',
    lat: 40.1176, lon: -82.9173,
    phone: '(614) 826-6549',
    website: 'https://www.fitclubwesterville.com',
    pricing: 'Contact for membership rates · Free intro class', monthlyPrice: 150.00, dayPassPrice: 0,
    openHour: 5, closeHour: 19,
    hoursDisplay: 'Mon–Fri 5–9AM & 4–7PM · Sat 7:30AM–Noon · Sun 8–11AM',
    passes: [], classes: ['HIIT', 'Boxing'], trainers: [], gymReviews: [],
    description: 'Westerville\'s premier CrossFit affiliate since 2008. Combines weightlifting, cardio, and bodyweight movements for constantly varied, high-intensity workouts. Personal training and Youth Athletic Development programs available. Community-focused environment welcoming all fitness levels. First class is free — contact to schedule a goal-setting intro session.',
    equipment: [
      { id: 'rg_fc_e1', name: 'Barbell & Bumper Plate Station', category: 'Free Weight', targetArea: 'Full Body, Olympic Lifts', minWeight: '45', maxWeight: '300', instructions: 'Coach will demonstrate proper form before each barbell movement. Never drop empty bars.', reviews: [] },
      { id: 'rg_fc_e2', name: 'Rig / Pull-Up Station', category: 'Machine', targetArea: 'Back, Arms, Core', minWeight: '0', maxWeight: '0', instructions: 'Use band assistance if needed. Kipping pull-ups taught after strict pull-up baseline established.', reviews: [] },
      { id: 'rg_fc_e3', name: 'Assault / Air Bike', category: 'Cardio', targetArea: 'Full Body, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'Maintain upright torso. Drive with both arms and legs. Pace yourself on longer intervals.', reviews: [] },
      { id: 'rg_fc_e4', name: 'Rowing Ergometers', category: 'Cardio', targetArea: 'Full Body, Back, Legs', minWeight: '0', maxWeight: '0', instructions: 'Strap feet in, legs-hips-arms on the drive. Arms-hips-legs on the recovery.', reviews: [] },
    ],
  },
  {
    id: 'rg_powershack_westerville', ownerID: 'rg_powershack', password: '',
    gymName: 'Power Shack Gym – Westerville', name: 'Power Shack Gym – Westerville',
    location: '6363 Cooper Rd, Columbus, OH 43231',
    lat: 40.0848, lon: -82.9468,
    phone: '(614) 898-9540',
    website: 'https://powershackgym.com/westerville/',
    pricing: 'Contact for rates · Multiple membership tiers', monthlyPrice: 40.00, dayPassPrice: 0,
    openHour: 5, closeHour: 22,
    hoursDisplay: 'Mon–Thu 5AM–10PM · Fri 5AM–9PM · Sat 8AM–6PM · Sun 9AM–7PM',
    passes: [], classes: [], trainers: [], gymReviews: [],
    description: 'Central Ohio\'s premier strength gym since 1990. Official Hammer Strength Training Center carrying Rogue, EliteFTS, Arsenal, Cybex, Life Fitness, Matrix, Precor, Star Trac, and Strive equipment. Specializes in high-quality free weights and unique pieces unavailable at chain gyms. Full cardio deck with treadmills, stair climbers, bikes, rowers, and ellipticals. Cable machines, plate-loaded machines, and circuits for all training styles. Four locations across Columbus.',
    equipment: [
      { id: 'rg_ps_e1', name: 'Hammer Strength Plate-Loaded Line', category: 'Machine', targetArea: 'Chest, Back, Legs, Shoulders', minWeight: '45', maxWeight: '700', instructions: 'Load plates evenly on both sides. Use full range of motion and controlled tempo.', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000', reviews: [] },
      { id: 'rg_ps_e2', name: 'Rogue Free Weight Area', category: 'Free Weight', targetArea: 'Full Body, Powerlifting', minWeight: '45', maxWeight: '1500', instructions: 'Full dumbbell and barbell selection. Squat racks and benches available. Collars required for barbell work.', image: 'https://images.unsplash.com/photo-1517343985841-f6b280e451b6?q=80&w=1000', reviews: [] },
      { id: 'rg_ps_e3', name: 'Cable Machine Station', category: 'Cable', targetArea: 'Full Body', minWeight: '10', maxWeight: '300', instructions: 'Adjust pulley height for the desired movement. Attach appropriate handle. Control weight through full range.', reviews: [] },
      { id: 'rg_ps_e4', name: 'Cardio Deck', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Full selection of treadmills, stair climbers, bikes, rowers, and ellipticals.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
    ],
  },
  {
    id: 'rg_metro_worthington', ownerID: 'rg_metro', password: '',
    gymName: 'Metro Fitness – Worthington', name: 'Metro Fitness – Worthington',
    location: '1245 Worthington Woods Blvd, Worthington, OH 43085',
    lat: 40.0897, lon: -83.0247,
    phone: '(614) 431-9999',
    website: 'https://metrofitnessohio.com/',
    pricing: 'Starting at $29.99/month', monthlyPrice: 29.99, dayPassPrice: 0,
    openHour: 4, closeHour: 23,
    hoursDisplay: 'Mon 5AM–Midnight · Tue–Thu 24hrs · Fri closes 10PM · Sat 6AM–6PM · Sun 9AM–6PM',
    passes: [], classes: ['Yoga', 'Group Fitness'], trainers: [], gymReviews: [],
    description: 'Central Ohio institution founded in 1986 and dedicated by Arnold Schwarzenegger. Now 18,000 sq ft of premium free weight and cardiovascular equipment. Extensive Hammer Strength selection, dedicated powerlifting room, iron plates, multiple racks, and open floor space for calisthenics. Welcoming to everyone from competitive bodybuilders to first-timers. Guest passes available at front desk.',
    equipment: [
      { id: 'rg_mfw_e1', name: 'Hammer Strength Equipment Suite', category: 'Machine', targetArea: 'Chest, Back, Legs, Shoulders, Arms', minWeight: '45', maxWeight: '800', instructions: 'Wide selection of Hammer Strength plate-loaded and selectorized machines. Load plates evenly.', image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000', reviews: [] },
      { id: 'rg_mfw_e2', name: 'Free Weight & Powerlifting Room', category: 'Free Weight', targetArea: 'Full Body, Powerlifting', minWeight: '45', maxWeight: '1500', instructions: 'Dedicated powerlifting area with competition-spec bars and plates. Multiple benches and racks.', image: 'https://images.unsplash.com/photo-1517343985841-f6b280e451b6?q=80&w=1000', reviews: [] },
      { id: 'rg_mfw_e3', name: 'Cardio Equipment Deck', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Full selection of treadmills, ellipticals, bikes, and stair climbers.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
      { id: 'rg_mfw_e4', name: 'Cable & Functional Training Area', category: 'Cable', targetArea: 'Full Body', minWeight: '10', maxWeight: '350', instructions: 'Multiple cable stations and functional training rigs. Open floor space available for calisthenics.', reviews: [] },
    ],
  },
  {
    id: 'rg_orangetheory_polaris', ownerID: 'rg_orangetheory', password: '',
    gymName: 'Orangetheory Fitness – Westerville', name: 'Orangetheory Fitness – Westerville',
    location: '823 Polaris Pkwy, Westerville, OH 43082',
    lat: 40.1548, lon: -82.9975,
    phone: '(614) 300-2925',
    website: 'https://www.orangetheory.com/en-us/locations/westerville-ohio-0722',
    pricing: 'Drop-in $28 · Memberships from ~$59/mo (Basic) to $159/mo (Premier)', monthlyPrice: 79.00, dayPassPrice: 28.00,
    openHour: 5, closeHour: 20,
    hoursDisplay: 'Class-based schedule · Contact studio for current times',
    passes: [], classes: ['HIIT', 'Cycling'], trainers: [], gymReviews: [],
    description: 'Science-backed heart rate-monitored HIIT training combining treadmill, rowing, and weight floor work. Real-time OTbeat™ heart rate display shown on studio screens. Members average 8.6% body fat loss and 2.6% lean muscle gain in 8 weeks of regular classes. Located in the Fresh Thyme Market Plaza near Polaris Mall, beside 101 Beer Kitchen. Look for the orange awnings.',
    equipment: [
      { id: 'rg_ot_e1', name: 'Treadmill Row', category: 'Cardio', targetArea: 'Legs, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'Coach directs base, push, and all-out paces. Hold side rails only briefly when adjusting speed.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
      { id: 'rg_ot_e2', name: 'WaterRower Rowing Machines', category: 'Cardio', targetArea: 'Full Body, Back, Legs', minWeight: '0', maxWeight: '0', instructions: 'Legs-body-arms on the drive; arms-body-legs on the recovery. Maintain a strong forward body angle at the catch.', image: 'https://images.unsplash.com/photo-1596357395104-caede1b6ab3d?q=80&w=1000', reviews: [] },
      { id: 'rg_ot_e3', name: 'Weight Floor (Dumbbells, TRX, Benches)', category: 'Free Weight', targetArea: 'Full Body, Strength', minWeight: '5', maxWeight: '50', instructions: 'Follow coach cues for the strength block. Use the OTbeat monitor to track effort during floor blocks.', reviews: [] },
    ],
  },
  {
    id: 'rg_westerville_community', ownerID: 'rg_wcc', password: '',
    gymName: 'Westerville Community Center', name: 'Westerville Community Center',
    location: '350 N Cleveland Ave, Westerville, OH 43082',
    lat: 40.1275, lon: -82.9197,
    phone: '(614) 901-6500',
    website: 'https://parks.westerville.org/facilities/community-center',
    pricing: 'Resident adult ~$26/mo · Non-resident adult ~$45/mo · Daily passes available', monthlyPrice: 26.00, dayPassPrice: 8.00,
    openHour: 5, closeHour: 22,
    hoursDisplay: 'Mon–Fri 5AM–10PM · Sat–Sun 7AM–8PM (approx. · confirm at website)',
    passes: [], classes: ['Yoga', 'Cycling', 'Zumba', 'Group Fitness', 'Pilates'], trainers: [], gymReviews: [],
    description: '145,000 sq ft municipal recreation center. Fitness area includes 3 squat racks, 2 Smith machines, 8-station cable crossover, Hammer Strength plate-loaded machines, dumbbells up to 100 lbs, and 70+ cardiovascular machines on the upper floor. Functional turf zone with rowers, Air Dynes, tire flip, weight sled, plyometric boxes, kettlebells and bands. Heated indoor pool, warm-water pool, hot tub, climbing wall, gymnasium, and esports room also included with pass. Silver Sneakers accepted. Group fitness and personal training available.',
    equipment: [
      { id: 'rg_wcc_e1', name: 'Strength Room – Squat Racks & Smith Machines', category: 'Free Weight', targetArea: 'Legs, Chest, Shoulders, Back', minWeight: '45', maxWeight: '600', instructions: '3 power racks and 2 Smith machines. Set safety bars before squatting. Multiple benches available.', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000', reviews: [] },
      { id: 'rg_wcc_e2', name: '8-Station Cable Crossover', category: 'Cable', targetArea: 'Chest, Back, Shoulders, Arms', minWeight: '10', maxWeight: '200', instructions: 'Adjust carriage heights independently for cable flies, rows, and chops. Select weight via pin.', reviews: [] },
      { id: 'rg_wcc_e3', name: 'Hammer Strength Plate-Loaded Line', category: 'Machine', targetArea: 'Chest, Back, Legs, Shoulders', minWeight: '45', maxWeight: '700', instructions: 'Full Hammer Strength line. Load plates evenly. Adjust seat to center your joints over the axis.', image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000', reviews: [] },
      { id: 'rg_wcc_e4', name: 'Cardiovascular Deck (70+ Machines)', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Upper floor has 70+ machines including treadmills, ellipticals, bikes, and stair climbers. Track alternates direction daily.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
      { id: 'rg_wcc_e5', name: 'Functional Turf Zone', category: 'Cardio', targetArea: 'Full Body, Athletic', minWeight: '0', maxWeight: '0', instructions: 'Area features rowers, Air Dynes, tire flip station, weight sled, plyo boxes, kettlebells, and resistance bands.', reviews: [] },
    ],
  },
  {
    id: 'rg_ymca_grovecity', ownerID: 'rg_ymca_gc', password: '',
    gymName: 'Grove City YMCA', name: 'Grove City YMCA',
    location: '3600 Discovery Dr, Grove City, OH 43123',
    lat: 39.8590, lon: -83.0774,
    phone: '(614) 871-9622',
    website: 'https://ymcacolumbus.org/locations/grovecity',
    pricing: 'Membership from ~$54/mo (household rates available)', monthlyPrice: 54.00, dayPassPrice: 10.00,
    openHour: 5, closeHour: 21,
    hoursDisplay: 'Mon–Fri 5AM–9PM · Sat 7AM–5PM · Sun 1PM–5PM',
    passes: [], classes: ['Yoga', 'Group Fitness', 'Cycling', 'Zumba'], trainers: [], gymReviews: [],
    description: 'Full-service YMCA branch with a dedicated wellness floor of cardio and strength equipment, an indoor pool, gymnasium, and group exercise studios. Youth and family programming, Silver Sneakers accepted, and financial assistance available for members who qualify. Personal training and swim lessons offered on-site.',
    equipment: [
      { id: 'rg_ymcagc_e1', name: 'Wellness Floor Cardio Deck', category: 'Cardio', targetArea: 'Cardiovascular System, Legs', minWeight: '0', maxWeight: '0', instructions: 'Treadmills, ellipticals, and bikes with TV mounts. Wipe down equipment after use per posted signage.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
      { id: 'rg_ymcagc_e2', name: 'Selectorized Strength Circuit', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '200', instructions: 'Adjust seat and pin weight before starting. Staff available for a free equipment orientation.', reviews: [] },
      { id: 'rg_ymcagc_e3', name: 'Free Weight Area', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '75', instructions: 'Dumbbells and adjustable benches. Return weights to the rack after each set.', reviews: [] },
      { id: 'rg_ymcagc_e4', name: 'Indoor Pool', category: 'Cardio', targetArea: 'Full Body, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'Lap lanes available during open swim hours; check the posted pool schedule at the front desk.', reviews: [] },
    ],
  },
  {
    id: 'rg_lafitness_hilliard', ownerID: 'rg_lafit_hilliard', password: '',
    gymName: 'LA Fitness – Hilliard', name: 'LA Fitness – Hilliard',
    location: '1800 Tanglewood Park Blvd, Hilliard, OH 43026',
    lat: 40.0209, lon: -83.1685,
    phone: '(614) 850-8888',
    website: 'https://www.lafitness.com/pages/clubhome.aspx?clubid=1003',
    pricing: 'Contact club for current membership rates', monthlyPrice: 34.99, dayPassPrice: 0,
    openHour: 5, closeHour: 23,
    hoursDisplay: 'Mon–Fri 5AM–11PM · Sat–Sun 7AM–7PM',
    passes: [], classes: ['Group Fitness', 'Cycling', 'HIIT'], trainers: [], gymReviews: [],
    description: 'Full-size health club with basketball courts, an indoor pool, group fitness studios, and a large free weight and machine floor. Sauna, whirlpool, and locker rooms included with membership. Kids Klub childcare available so parents can train without interruption.',
    equipment: [
      { id: 'rg_laf_e1', name: 'Selectorized Machine Floor', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '300', instructions: 'Wide range of Cybex and Hammer Strength machines. Wipe down after use.', image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000', reviews: [] },
      { id: 'rg_laf_e2', name: 'Free Weight & Squat Rack Area', category: 'Free Weight', targetArea: 'Full Body, Powerlifting', minWeight: '45', maxWeight: '500', instructions: 'Multiple squat racks and a full dumbbell range up to 100 lbs. Use collars on loaded barbells.', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000', reviews: [] },
      { id: 'rg_laf_e3', name: 'Cardio Theater', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Treadmills, ellipticals, and bikes with personal TV screens.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
      { id: 'rg_laf_e4', name: 'Indoor Pool & Whirlpool', category: 'Cardio', targetArea: 'Full Body, Recovery', minWeight: '0', maxWeight: '0', instructions: 'Lap swim and open swim hours posted at the pool entrance. Shower before entering.', reviews: [] },
    ],
  },
  {
    id: 'rg_arena_district', ownerID: 'rg_arena', password: '',
    gymName: 'Arena District Athletic Club', name: 'Arena District Athletic Club',
    location: '325 John H. McConnell Blvd, Suite 150, Columbus, OH 43215',
    lat: 39.9695, lon: -83.0033,
    phone: '(614) 224-3488',
    website: 'https://www.arenaathletic.com/',
    pricing: 'Contact club for membership pricing', monthlyPrice: 89.00, dayPassPrice: 20.00,
    openHour: 5, closeHour: 22,
    hoursDisplay: 'Mon–Fri 5AM–10PM · Sat–Sun 7AM–6PM',
    passes: [], classes: ['HIIT', 'Group Fitness'], trainers: [], gymReviews: [],
    description: 'Upscale athletic club in the heart of the Arena District, steps from Nationwide Arena. Boutique-style strength and cardio floor, group fitness studio, and personal training suites. Popular with downtown professionals for its convenient location and locker room amenities including towel service.',
    equipment: [
      { id: 'rg_ada_e1', name: 'Premium Strength Floor', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '300', instructions: 'Life Fitness selectorized line. Wipe equipment down after each use.', image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000', reviews: [] },
      { id: 'rg_ada_e2', name: 'Free Weight Studio', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '100', instructions: 'Dumbbells, benches, and a dedicated squat rack area. Racking weights is required after use.', reviews: [] },
      { id: 'rg_ada_e3', name: 'Cardio Deck with City Views', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Treadmills and bikes overlooking the Arena District. Reserve equipment during peak lunch hours if busy.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
    ],
  },
  {
    id: 'rg_crossfit_gahanna', ownerID: 'rg_cf_gahanna', password: '',
    gymName: 'CrossFit Gahanna', name: 'CrossFit Gahanna',
    location: '145 S Stygler Rd, Gahanna, OH 43230',
    lat: 40.0119, lon: -82.8586,
    phone: '(614) 414-6022',
    website: 'https://www.crossfitgahanna.com/',
    pricing: 'Contact for membership rates · Free intro class', monthlyPrice: 155.00, dayPassPrice: 0,
    openHour: 5, closeHour: 20,
    hoursDisplay: 'Mon–Fri 5:30AM–7:30PM · Sat 8AM–11AM',
    passes: [], classes: ['HIIT', 'Boxing'], trainers: [], gymReviews: [],
    description: 'Community-driven CrossFit affiliate serving Gahanna and the northeast Columbus suburbs. Coached group classes combine Olympic lifting, gymnastics, and metabolic conditioning. Scaling options offered for every movement so beginners and competitive athletes train side by side. On-ramp program required for new members.',
    equipment: [
      { id: 'rg_cfg_e1', name: 'Barbell & Bumper Plate Station', category: 'Free Weight', targetArea: 'Full Body, Olympic Lifts', minWeight: '45', maxWeight: '300', instructions: 'Coached technique work required before loading heavy. Never drop an empty barbell.', reviews: [] },
      { id: 'rg_cfg_e2', name: 'Pull-Up Rig', category: 'Machine', targetArea: 'Back, Arms, Core', minWeight: '0', maxWeight: '0', instructions: 'Bands available for assisted pull-ups. Ring and bar attachments rotate by WOD.', reviews: [] },
      { id: 'rg_cfg_e3', name: 'Rowing Ergometers', category: 'Cardio', targetArea: 'Full Body, Back, Legs', minWeight: '0', maxWeight: '0', instructions: 'Strap feet snugly. Drive legs-hips-arms, recover arms-hips-legs.', image: 'https://images.unsplash.com/photo-1596357395104-caede1b6ab3d?q=80&w=1000', reviews: [] },
    ],
  },
  {
    id: 'rg_lifetime_dublin', ownerID: 'rg_lt_dublin', password: '',
    gymName: 'Life Time – Dublin', name: 'Life Time – Dublin',
    location: '3825 Hard Rd, Dublin, OH 43016',
    lat: 40.1189, lon: -83.1418,
    phone: '(614) 764-1144',
    website: 'https://www.lifetime.life/locations/oh/dublin.html',
    pricing: 'Contact club for membership pricing', monthlyPrice: 129.00, dayPassPrice: 25.00,
    openHour: 4, closeHour: 23,
    hoursDisplay: 'Mon–Fri 4AM–11PM · Sat–Sun 6AM–10PM',
    passes: [], classes: ['Yoga', 'Cycling', 'HIIT', 'Group Fitness'], trainers: [], gymReviews: [],
    description: 'Premium athletic resort with an expansive strength and cardio floor, indoor and outdoor pools, basketball courts, a spa, and a full schedule of studio classes. LifeCafe on-site for post-workout meals. Kids Academy childcare included with most membership tiers.',
    equipment: [
      { id: 'rg_ltd_e1', name: 'Full Strength & Machine Floor', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '400', instructions: 'Extensive selectorized and plate-loaded equipment. Staff floor coaches available for form checks.', image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000', reviews: [] },
      { id: 'rg_ltd_e2', name: 'Free Weight & Powerlifting Zone', category: 'Free Weight', targetArea: 'Full Body, Powerlifting', minWeight: '45', maxWeight: '1000', instructions: 'Dedicated racks, platforms, and a full dumbbell range up to 120 lbs.', image: 'https://images.unsplash.com/photo-1517343985841-f6b280e451b6?q=80&w=1000', reviews: [] },
      { id: 'rg_ltd_e3', name: 'Indoor/Outdoor Pool Complex', category: 'Cardio', targetArea: 'Full Body, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'Lap lanes, a leisure pool, and outdoor pool seasonally. Check posted lane etiquette signage.', reviews: [] },
      { id: 'rg_ltd_e4', name: 'Cardio Cinema Deck', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Rows of treadmills, bikes, and ellipticals facing a large screen. Personal TVs also available.', image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?q=80&w=1000', reviews: [] },
    ],
  },
  {
    id: 'rg_crossfit_newalbany', ownerID: 'rg_cf_newalbany', password: '',
    gymName: 'CrossFit New Albany', name: 'CrossFit New Albany',
    location: '5900 Zarley Street, New Albany, OH 43054',
    lat: 40.0762, lon: -82.8090,
    phone: '(614) 216-9552',
    website: 'https://www.crossfitnewalbany.com/',
    pricing: 'Contact for membership rates · Free intro session', monthlyPrice: 160.00, dayPassPrice: 0,
    openHour: 5, closeHour: 19,
    hoursDisplay: 'Mon–Fri 5:30AM–7PM · Sat 8AM–10AM',
    passes: [], classes: ['HIIT', 'Boxing'], trainers: [], gymReviews: [],
    description: 'Boutique CrossFit box serving New Albany and the surrounding northeast Columbus suburbs. Small class sizes with individualized coaching cues on every lift. Nutrition coaching and a strong member community with regular in-house competitions and social events.',
    equipment: [
      { id: 'rg_cfna_e1', name: 'Olympic Lifting Platforms', category: 'Free Weight', targetArea: 'Full Body, Olympic Lifts', minWeight: '45', maxWeight: '300', instructions: 'Dedicated platforms for snatch and clean & jerk work. Bumper plates only on platforms.', reviews: [] },
      { id: 'rg_cfna_e2', name: 'Assault Air Bike', category: 'Cardio', targetArea: 'Full Body, Cardiovascular', minWeight: '0', maxWeight: '0', instructions: 'Maintain an upright torso and drive with both arms and legs simultaneously.', reviews: [] },
      { id: 'rg_cfna_e3', name: 'Gymnastics Rig', category: 'Machine', targetArea: 'Back, Core, Arms', minWeight: '0', maxWeight: '0', instructions: 'Rings, bars, and rope attachments rotate based on the daily programming.', reviews: [] },
    ],
  },
  {
    id: 'rg_planet_reynoldsburg', ownerID: 'rg_planet3', password: '',
    gymName: 'Planet Fitness – Reynoldsburg', name: 'Planet Fitness – Reynoldsburg',
    location: '7088 E Main St, Reynoldsburg, OH 43068',
    lat: 39.9556, lon: -82.7908,
    phone: '(614) 810-1600',
    website: 'https://www.planetfitness.com/gyms/reynoldsburg-oh/',
    pricing: 'Classic $15/mo · Black Card $25/mo', monthlyPrice: 15.00, dayPassPrice: 0,
    openHour: 0, closeHour: 0,
    hoursDisplay: 'Open 24 hours, 7 days a week',
    passes: [], classes: ['Group Fitness'], trainers: [], gymReviews: [],
    description: 'Judgment Free Zone® location serving Reynoldsburg and the east side of Columbus. Full cardio and strength machine circuit with free fitness training included. Black Card members get access to all Planet Fitness locations nationwide plus HydroMassage and tanning.',
    equipment: [
      { id: 'rg_pf3_e1', name: 'Cardio Zone', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Full range of treadmills, ellipticals, bikes, and stairclimbers.', reviews: [] },
      { id: 'rg_pf3_e2', name: 'Strength Machine Circuit', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '250', instructions: 'Guided 30-minute Express Circuit or open-floor training available.', reviews: [] },
      { id: 'rg_pf3_e3', name: 'Free Weight Area', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '80', instructions: 'Dumbbell range and benches on the floor. Use collars on barbells.', reviews: [] },
    ],
  },
  {
    id: 'rg_delaware_fit_factory', ownerID: 'rg_delaware_ff', password: '',
    gymName: 'Delaware Fit Factory', name: 'Delaware Fit Factory',
    location: '171 S Sandusky St, Delaware, OH 43015',
    lat: 40.2967, lon: -83.0685,
    phone: '(740) 417-1198',
    website: 'https://www.facebook.com/DelawareFitFactory/',
    pricing: 'Contact for personal training and membership rates', monthlyPrice: 45.00, dayPassPrice: 0,
    openHour: 5, closeHour: 20,
    hoursDisplay: 'Mon–Fri 5AM–8PM · Sat 8AM–Noon',
    passes: [], classes: ['HIIT', 'Group Fitness'], trainers: [], gymReviews: [],
    description: 'Locally-owned strength and conditioning studio in downtown Delaware, about 25 miles north of Columbus. Small-group and one-on-one personal training with a focus on functional strength. Popular with athletes from nearby Ohio Wesleyan University as well as local residents.',
    equipment: [
      { id: 'rg_dff_e1', name: 'Free Weight Training Area', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '200', instructions: 'Dumbbells, kettlebells, and a squat rack. Coaches available to spot heavier lifts.', reviews: [] },
      { id: 'rg_dff_e2', name: 'Turf & Sled Zone', category: 'Cardio', targetArea: 'Full Body, Athletic', minWeight: '0', maxWeight: '0', instructions: 'Weight sled, battle ropes, and agility ladder area on the turf strip.', reviews: [] },
      { id: 'rg_dff_e3', name: 'Cable Functional Trainer', category: 'Cable', targetArea: 'Full Body', minWeight: '10', maxWeight: '200', instructions: 'Dual-adjustable pulley station. Select handle attachment and pin weight before starting.', reviews: [] },
    ],
  },
  {
    id: 'rg_ua_fitness', ownerID: 'rg_ua_fit', password: '',
    gymName: 'UA Fitness', name: 'UA Fitness',
    location: '2100 Tremont Ctr, Upper Arlington, OH 43221',
    lat: 40.0106, lon: -83.0559,
    phone: '(614) 486-0575',
    website: 'https://chamberofcommerce.com/united-states/ohio/upper-arlington/gym/2005185646-ua-fitness',
    pricing: '24-hour keyfob access · contact for monthly rate', monthlyPrice: 39.99, dayPassPrice: 0,
    openHour: 0, closeHour: 0,
    hoursDisplay: 'Open 24 hours (keyfob access), staffed hours vary',
    passes: [], classes: ['Group Fitness'], trainers: [], gymReviews: [],
    description: 'Independently owned neighborhood gym in the Tremont Center area of Upper Arlington. Old-school strength floor with a deep free weight selection alongside modern cardio equipment. No-frills, no-contract atmosphere popular with long-time locals.',
    equipment: [
      { id: 'rg_uaf_e1', name: 'Free Weight Floor', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '150', instructions: 'Deep dumbbell range and multiple flat/incline benches. Re-rack plates after use.', reviews: [] },
      { id: 'rg_uaf_e2', name: 'Plate-Loaded Machine Row', category: 'Machine', targetArea: 'Chest, Back, Legs', minWeight: '45', maxWeight: '400', instructions: 'Classic plate-loaded machines. Load evenly on both sides before use.', reviews: [] },
      { id: 'rg_uaf_e3', name: 'Cardio Corner', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Treadmills, a couple of bikes, and a stairclimber near the front windows.', reviews: [] },
    ],
  },
  {
    id: 'rg_violet_community_fitness', ownerID: 'rg_violet_pick', password: '',
    gymName: 'Violet Community Fitness', name: 'Violet Community Fitness',
    location: '140 West Borland Street, Ste 300, Pickerington, OH 43147',
    lat: 39.8988, lon: -82.7660,
    phone: '(614) 321-9097',
    website: 'https://www.violetcommunityfitness.com/',
    pricing: 'Community-rate memberships · contact for pricing', monthlyPrice: 30.00, dayPassPrice: 10.00,
    openHour: 5, closeHour: 21,
    hoursDisplay: 'Mon–Fri 5AM–9PM · Sat–Sun 8AM–2PM',
    passes: [], classes: ['Yoga', 'Group Fitness', 'Zumba'], trainers: [], gymReviews: [],
    description: 'Nonprofit, community-focused fitness center in downtown Pickerington. Affordable membership tiers with an emphasis on accessibility for local families and seniors. Group fitness studio, walking track, and a modest strength/cardio floor.',
    equipment: [
      { id: 'rg_vcf_e1', name: 'Strength & Cardio Floor', category: 'Machine', targetArea: 'Full Body', minWeight: '10', maxWeight: '200', instructions: 'Selectorized machines and a small cardio row. Staff on-site for equipment orientations.', reviews: [] },
      { id: 'rg_vcf_e2', name: 'Free Weight Rack', category: 'Free Weight', targetArea: 'Full Body', minWeight: '5', maxWeight: '60', instructions: 'Dumbbells up to 60 lbs and an adjustable bench. Please share equipment during busy hours.', reviews: [] },
      { id: 'rg_vcf_e3', name: 'Indoor Walking Track', category: 'Cardio', targetArea: 'Cardiovascular, Legs', minWeight: '0', maxWeight: '0', instructions: 'Track loops the upper level of the gymnasium. Walk/run in the posted direction of the day.', reviews: [] },
    ],
  },
];
